function report = batch_analysis_selfcheck(referenceRoot)
%BATCH_ANALYSIS_SELFCHECK Exercise reporting before either expensive run.
% Synthetic application tables only; this function never creates a simulator.
if nargin<1
    referenceRoot=fullfile(fileparts(fileparts(mfilename('fullpath'))),'reference');
end
root=tempname; mkdir(root); cleanup=onCleanup(@() removeTemporary(root)); %#ok<NASGU>
[result,applications]=syntheticMatlab();
toyReference=fullfile(root,'toy_reference'); mkdir(toyReference);
writeToyReference(toyReference);
toyCase=fullfile(root,'toy_case'); mkdir(toyCase);
summary=batch_case_analysis(result,applications,toyCase,toyReference,15);
assert(summary.completed && ~summary.acceptance_established && ~summary.network_parity_established, ...
    'csr6000:Selfcheck','Reporting completion must not claim network acceptance.');
assert(summary.totals.matlab.admitted==9 && summary.totals.matlab.delivered==7 && ...
    summary.totals.matlab.raw_model_dropped==1 && summary.totals.matlab.raw_model_pending==1, ...
    'csr6000:Selfcheck','Synthetic MATLAB outcomes do not close.');
assert(summary.totals.matlab.unresolved_at_cutoff==2 && ...
    summary.totals.matlab.undelivered_total==2 && ...
    summary.totals.matlab.proven_terminal_drop_lower_bound==0 && ...
    ~summary.totals.matlab.terminal_drop_total_known, ...
    'csr6000:Selfcheck','Provisional raw drops must remain unresolved, with final-loss split unknown.');
assert(summary.totals.native.admitted==8 && summary.totals.native.delivered==7 && ...
    summary.totals.native.delivery_events==8 && summary.totals.native.duplicate_delivery_events==1 && ...
    isnan(summary.totals.native.raw_model_dropped) && isnan(summary.totals.native.raw_model_pending), ...
    'csr6000:Selfcheck','Native duplicates or unknown terminal fate were mishandled.');
c=summary.source_comparisons;
assert(strcmp(c(1).delivered_comparison_status,'both_zero_counts_equal_relative_undefined') && ...
    ~c(1).delivered_relative_defined && isnan(c(1).delivered_target_pass), ...
    'csr6000:Selfcheck','Zero-zero count comparison must remain separate.');
assert(strcmp(c(5).delivered_comparison_status,'undefined_zero_native_reference') && ...
    strcmp(c(6).latency_comparison_status,'undefined_zero_native_reference') && ...
    ~c(6).latency_relative_defined && c(4).delivered_target_pass==0 && ...
    ~c(4).latency_relative_defined, 'csr6000:Selfcheck','Undefined or failed source metrics changed.');
a=summary.source_accounting;
assert(abs(a(2).mean_delivered_latency_s-476)<1e-9 && ...
    abs(a(2).p95_delivered_latency_s-1160)<1e-9, ...
    'csr6000:Selfcheck','Delivered-only mean or core quantile differs.');
weighted=summary.native_delivery_weighted_latency;
assert(isequal(weighted.common_sources,[3 8]) && abs(weighted.weights(2)-5/6)<1e-12 && ...
    abs(weighted.weights(6)-1/6)<1e-12 && abs(weighted.matlab_weighted_mean_latency_s-2380/6)<1e-9 && ...
    weighted.matlab_excluded_deliveries==1 && weighted.native_excluded_deliveries==1, ...
    'csr6000:Selfcheck','Common-source weighting or excluded population changed.');
h=readtable(fullfile(toyCase,'analysis','fixed_age_delivery.csv'),'TextType','string');
assert(height(h)==56,'csr6000:Selfcheck','Expected both models, all sources and pooled rows at four horizons.');
for k=1:4
    horizons=[60 300 600 1200]; counts=[282000 270000 255000 225000];
    chosen=h.source==3 & h.horizon_s==horizons(k);
    assert(all(h.scheduled_attempts(chosen)==counts(k)), ...
        'csr6000:Selfcheck','Half-open scheduled population is incorrect.');
end
chosen=h.model=="matlab" & h.source==3 & h.horizon_s==60;
assert(sum(chosen)==1 && h.admitted(chosen)==4 && h.delivered_by_age(chosen)==1 && ...
    h.delivered_later_by_stop(chosen)==3 && abs(h.fraction_of_admitted(chosen)-0.25)<1e-12, ...
    'csr6000:Selfcheck','Exact deadline or upper generation boundary was mishandled.');
chosen=h.model=="matlab" & h.source==3 & h.horizon_s==1200;
assert(h.admitted(chosen)==3 && h.delivered_by_age(chosen)==3, ...
    'csr6000:Selfcheck','1200-second boundary must exclude generation at exactly4800 seconds.');
unfinished=readtable(fullfile(toyCase,'analysis','matlab_unfinished.csv'),'TextType','string');
pending=unfinished.app_id==4;
assert(height(unfinished)==2 && unfinished.last_observed_custody_node(pending)==4 && ...
    unfinished.last_observed_custody_time_s(pending)==320 && ...
    unfinished.age_at_cutoff_s(pending)==5700 && ~any(unfinished.age_proves_live_queued_copy), ...
    'csr6000:Selfcheck','Unfinished ages or custody evidence semantics changed.');
assert(all(unfinished.status=="unresolved_at_cutoff") && ...
    sum(unfinished.raw_model_outcome=="dropped")==1 && ...
    sum(unfinished.raw_model_outcome=="pending")==1, ...
    'csr6000:Selfcheck','Unfinished ledger must preserve raw outcomes without declaring final loss.');

realChecks=repmat(struct('seed',0,'completed',false,'native_admitted',0, ...
    'native_unique_delivered',0,'native_duplicate_delivery_events',0),2,1);
for k=1:2
    seed=130+k; result.Config.Seed=seed;
    directory=fullfile(root,sprintf('real_reference_s%d',seed)); mkdir(directory);
    reference=fullfile(referenceRoot,sprintf('s%d',seed));
    checked=batch_case_analysis(result,applications,directory,reference,15);
    fixture=readtable(fullfile(reference,'applications.csv'),'TextType','string','VariableNamingRule','preserve');
    delivered=string(fixture.status)=="delivered";
    duplicates=sum(double(fixture.delivery_event_count))-sum(delivered);
    assert(checked.completed && checked.totals.native.admitted==height(fixture) && ...
        checked.totals.native.delivered==sum(delivered) && ...
        checked.totals.native.duplicate_delivery_events==duplicates, ...
        'csr6000:Selfcheck','Real native reference schema or duplicate-event handling failed.');
    if seed==132
        assert(duplicates==4,'csr6000:Selfcheck','Pinned seed132 reference duplicate-event count changed.');
    end
    realChecks(k)=struct('seed',seed,'completed',true,'native_admitted',height(fixture), ...
        'native_unique_delivered',sum(delivered),'native_duplicate_delivery_events',duplicates);
end
report=struct('schema','csr6000-analysis-selfcheck-v2','completed',true, ...
    'simulation_executed',false,'synthetic_outcomes_verified',true, ...
    'undefined_reference_metrics_verified',true,'native_duplicate_events_verified',true, ...
    'all_four_half_open_horizons_verified',true,'deadline_equality_verified',true, ...
    'common_source_weights_verified',true,'unfinished_age_semantics_verified',true, ...
    'provisional_drop_semantics_verified',true, ...
    'real_native_reference_checks',realChecks, ...
    'scope','Reporter execution over synthetic MATLAB outcomes and both actual bundled native references; no network simulation or parity claim.');
end

function [result,a]=syntheticMatlab()
sources=[2 3 4 5 7 8];
flows=repmat(struct('SourceId',0,'DestinationId',1,'StartSeconds',300, ...
    'IntervalSeconds',0.02,'PacketCount',285000),1,6);
for k=1:6, flows(k).SourceId=sources(k); end
source=[3;3;4;5;7;8;3;3;3]; generated=[300;5940;300;300;300;300;301;4800;4799.98];
received=[360;5999;NaN;NaN;360;300;362;5800;5999.98];
outcome=["delivered";"delivered";"dropped";"pending";"delivered";"delivered";"delivered";"delivered";"delivered"];
dropReason=strings(9,1); dropReason(3)="retry_exhausted";
a=table(uint64((1:9)'),source,ones(9,1),generated,received,received-generated,outcome,dropReason, ...
    'VariableNames',{'PacketId','SourceId','DestinationId','GeneratedSeconds', ...
    'ReceivedSeconds','LatencySeconds','Outcome','DropReason'});
admitted=zeros(6,1);
for k=1:6, admitted(k)=sum(source==sources(k)); end
counts=table(sources',ones(6,1),repmat(285000,6,1),admitted,zeros(6,1),zeros(6,1), ...
    zeros(6,1),zeros(6,1),285000-admitted,'VariableNames',{'SourceId','ConfiguredDestinationId', ...
    'Attempts','Admitted','BlockedDiscovery','BlockedTopology','BlockedGatewayRoute','BlockedDestination','BlockedNsdp'});
trace=table({'relay_accept'},uint64(4),4,320, ...
    'VariableNames',{'Event','PacketId','NodeId','TimeSeconds'});
result=struct('Config',struct('Seed',131,'DurationSeconds',6000,'Traffic',flows), ...
    'Statistics',struct('Generated',9,'Received',7,'Dropped',1,'Pending',1), ...
    'ApplicationAdmissionStatistics',counts,'ProtocolTrace',trace);
end

function writeToyReference(directory)
source=[3;3;3;3;3;4;5;8]; generated=[300;5940;301;4800;4799.98;300;300;300];
received=[360;5999;362;5800;5999.98;NaN;400;300];
delivered=isfinite(received); status=repmat("delivered",8,1); status(~delivered)="unresolved_at_cutoff";
events=double(delivered); events(1)=2;
native=table(repmat("native",8,1),repmat(131,8,1),source,ones(8,1),(101:108)', ...
    round((generated-300)/0.02),round(generated*1e9),round(generated*1e9), ...
    round(received*1e9),events,status,repmat(6000e9,8,1), ...
    round(received*1e9)-round(generated*1e9),zeros(8,1), ...
    'VariableNames',{'model','seed','source','destination','native_app_id','attempt_index_0based', ...
    'generated_time_ns','source_admitted_time_ns','first_delivery_time_ns','delivery_event_count', ...
    'status','cutoff_ns','latency_ns','proven_terminal_drop_count_lower_bound'});
writetable(native,fullfile(directory,'applications.csv'));
sources=[2;3;4;5;7;8]; admitted=zeros(6,1);
for k=1:6, admitted(k)=sum(source==sources(k)); end
counts=table(sources,ones(6,1),repmat(285000,6,1),admitted,zeros(6,1),zeros(6,1), ...
    zeros(6,1),zeros(6,1),285000-admitted, ...
    'VariableNames',{'source','configured_destination','attempts','admitted','blocked_discovery', ...
    'blocked_topology','blocked_gateway_route','blocked_destination','blocked_nsdp'});
writetable(counts,fullfile(directory,'app-admission-diagnostics.csv'));
end

function removeTemporary(path)
if isfolder(path), rmdir(path,'s'); end
end
