function options = defaults()
%DEFAULTS Portable NWK options; discovery is explicit and custody is bounded.
options = struct('StartupMode','gateway','StartupDelaySeconds',10, ...
    'DiscoveryDurationSeconds',30,'QueueLimit',512,'ControlQueueLimit',64, ...
    'ControlRetrySeconds',8,'MaxControlCycles',3,'RouteRequestSeconds',8, ...
    'MaxRouteRequests',2,'SnapshotWatchdogSeconds',20, ...
    'GatewayWatchdogSeconds',60,'MaxHopCount',32, ...
    'AdaptiveLinkControl',true,'SendOnlyToGateway',false, ...
    'Neighbor',csr.nwk.Neighbors.defaults(),'Routing',csr.nwk.Routes.defaults(), ...
    'Reassembly',struct('MaxMessages',64,'MaxMessagesPerPeer',8));
end
