function [cases,plan] = linkDiagnosticSuite()
%LINKDIAGNOSTICSUITE Fixed five-seed admission/contention observations.
% The input plan names new experiments; accepted T7 inputs are unchanged.
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
path=fullfile(root,'scenarios','link_diagnostics','plan.json');
plan=jsondecode(fileread(path));
pin='486d9e01f010fdfd4c6aebb87c6d7e51fc674a5b';
if ~strcmp(plan.schema,'csr-link-diagnostic-plan-v1') || ...
        ~strcmp(plan.ns3_source_commit,pin) || plan.case_count~=10 || ...
        ~isequal(plan.seeds(:)',128:132) || numel(plan.cases)~=10
    error('csr:diagnostic:Plan','Expected the pinned two-fixture, five-seed plan.');
end
entries=plan.cases;
if iscell(entries), entries=vertcat(entries{:}); end
template=struct('CaseId','','BaseCaseId','','Scenario','','ScenarioFile','', ...
    'ScenarioSHA256','','ProfileId','','DurationSeconds',0,'Seed',0, ...
    'BucketWidthSeconds',0,'SourceKind','','OpnetAvailable',false, ...
    'ReferenceDirectory','','ObserverMaxRecords',0,'Config',struct());
cases=repmat(template,numel(entries),1);
names={entries.case_id};
if numel(unique(names))~=10, error('csr:diagnostic:Plan','Duplicate diagnostic case.'); end
for k=1:numel(entries)
    item=entries(k);
    expectedSeed=128+floor((k-1)/2);
    bases={'two_node_admission_1200','three_node_contention_360'};
    base=bases{1+mod(k-1,2)};
    if ~strcmp(item.base_case_id,base) || item.seed~=expectedSeed || ...
            ~strcmp(item.case_id,sprintf('%s_s%d',base,expectedSeed)) || ...
            ~strcmp(item.source_kind,'synthetic_multiseed_diagnostic') || item.opnet_available
        error('csr:diagnostic:Plan','Unexpected fixture, order, seed or provenance.');
    end
    if isempty(regexp(item.scenario_file,'^scenarios/link_diagnostics/inputs/[a-zA-Z0-9_-]+\.csv$','once')) || ...
            isempty(regexp(item.recipe_file,'^scenarios/link_diagnostics/inputs/[a-zA-Z0-9_-]+\.recipe\.json$','once')) || ...
            ~strcmp(item.reference_directory,['evidence/tranche-8-ns3-reference/' item.case_id])
        error('csr:diagnostic:Plan','Diagnostic paths must be canonical relative paths.');
    end
    input=fullfile(root,item.scenario_file);
    recipePath=fullfile(root,item.recipe_file);
    if ~strcmp(csr.validation.Artifacts.sha256(input),item.scenario_sha256) || ...
            ~strcmp(csr.validation.Artifacts.sha256(recipePath),item.recipe_sha256)
        error('csr:diagnostic:InputChanged','Diagnostic input or recipe hash changed.');
    end
    recipe=jsondecode(fileread(recipePath));
    if ~strcmp(recipe.schema,'csr-link-diagnostic-derivation-v1') || ...
            ~strcmp(recipe.base_case_id,base) || ...
            ~strcmp(recipe.parent_scenario,['scenarios/benchmarks/' base '.csv']) || ...
            ~strcmp(csr.validation.Artifacts.sha256(fullfile(root,recipe.parent_scenario)), ...
                recipe.parent_scenario_sha256) || ...
            ~strcmp(recipe.overrides.scenario,item.scenario) || recipe.overrides.seed~=item.seed
        error('csr:diagnostic:InputChanged','Diagnostic parent or derivation changed.');
    end
    config=csr.scenario.importNs3(input,struct('HistoricalBenchmark',true, ...
        'FlowLimit',item.flow_limit,'Backend','portable'));
    if ~strcmp(config.Name,item.scenario) || config.Seed~=item.seed || ...
            config.DurationSeconds~=item.duration_s || ...
            ~strcmp(config.SharedScenario.HopSecurityProfile,item.profile_id)
        error('csr:diagnostic:Plan','Imported scenario differs from its plan.');
    end
    config.Trace.MaxRecords=item.trace_limits.protocol;
    config.Trace.MaxPhyRecords=item.trace_limits.phy;
    config.Trace.MaxApplicationAdmissionRecords=item.trace_limits.admission;
    config.MaxEvents=12000000;
    config.Benchmark=struct('Schema','csr-matlab-benchmark-v1', ...
        'CaseId',item.case_id,'SourceKind',item.source_kind,'ProfileId',item.profile_id, ...
        'OpnetAvailable',false,'BucketWidthSeconds',item.bucket_width_s, ...
        'ReferenceDirectory',item.reference_directory, ...
        'CatalogSHA256',csr.validation.Artifacts.sha256(path), ...
        'HistoricalOutcomeEquivalenceEstablished',false);
    config=csr.scenario.validate(config);
    if item.trace_limits.link_decisions~=item.trace_limits.feedback_transmissions || ...
            item.trace_limits.link_decisions~=100000
        error('csr:diagnostic:Plan','Unexpected observation trace limits.');
    end
    cases(k)=struct('CaseId',item.case_id,'BaseCaseId',base,'Scenario',item.scenario, ...
        'ScenarioFile',item.scenario_file,'ScenarioSHA256',item.scenario_sha256, ...
        'ProfileId',item.profile_id,'DurationSeconds',item.duration_s,'Seed',item.seed, ...
        'BucketWidthSeconds',item.bucket_width_s,'SourceKind',item.source_kind, ...
        'OpnetAvailable',false,'ReferenceDirectory',item.reference_directory, ...
        'ObserverMaxRecords',item.trace_limits.link_decisions,'Config',config);
end
end
