function report = networkTimingContract(outputDirectory)
%NETWORKTIMINGCONTRACT Paired receiver timing in the real network and PHY.
% Structural accounting is required; finite-stop losses and backlog remain
% measurements. Independent native RNG prevents an exact trace-parity gate.
if nargin<1 || isempty(outputDirectory)
    error('csr:t16:Output','An evidence directory is required for the network experiment.');
end
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
[cases,plan]=csr.scenario.tranche16Suite();
if ~isequal(plan.service_window_seconds(:)',[300 320]) || ...
        ~isequal(plan.service_window_end_exclusive,true) || ...
        plan.timing_max_records~=100000 || plan.service_max_records~=100000
    error('csr:t16:Plan','Unexpected timing capacity or service observation window.');
end
if ~isfolder(outputDirectory), mkdir(outputDirectory); end
snapshot=csr.validation.Artifacts.sourceSnapshot(root);
sourcePath=fullfile(outputDirectory,'source.json');
csr.validation.Artifacts.writeJson(sourcePath,snapshot);
sourceHash=csr.validation.Artifacts.sha256(sourcePath);
report=struct('Schema','csr-tranche16-network-timing-contract-v1', ...
    'DiagnosticCompleted',false,'Passed',false,'ModeCount',2,'CaseCount',0, ...
    'PlannedCaseCount',12,'CheckpointCount',0,'FailedCount',0, ...
    'SimulatedSecondsCompleted',0,'PlannedSimulatedSeconds',9360, ...
    'PlanSHA256',csr.validation.Artifacts.sha256(fullfile(root,'scenarios','t16','plan.json')), ...
    'SourceSnapshotSHA256',sourceHash,'Runtime',version, ...
    'NumericalParityEstablished',false,'FullAcceptanceEstablished',false, ...
    'ServiceWindowSeconds',[300 320],'TimingMaxRecords',100000, ...
    'ObserverMaxRecords',100000,'Cases',struct([]), ...
    'Scope',['Six unchanged real-PHY fixtures, paired across receiver callback timing policies; ' ...
        'full-run feedback, rate/power and admission records, with service callbacks in [300,320) seconds. ' ...
        'Original PHY calculations, TX/MAC timers and default policy remain unchanged.']);
checks=repmat(checkTemplate(),0,1); summaries=cell(0,1);
policies={'continuous','nanoseconds'}; keys={'c','n'};
started=tic; writeReport();
for k=1:numel(cases)
    item=cases(k);
    for m=1:2
        mode=policies{m}; key=keys{m};
        relative=[key '/' item.StorageKey]; folder=fullfile(outputDirectory,key,item.StorageKey);
        if isfolder(folder), error('csr:t16:OutputExists','Case output already exists: %s.',folder); end
        mkdir(folder);
        fprintf('\nNetwork timing %d/%d: %s, %s (%g simulated seconds).\n', ...
            report.CaseCount+1,12,item.StorageKey,mode,item.DurationSeconds);
        observer=csr.sim.AckServiceDiagnostics(100000,[300 320]);
        timing=csr.sim.TransportTiming(mode,100000);
        completedResult=false;
        try
            simulation=csr.sim.NetworkSimulation(item.Config,observer,timing);
            result=simulation.run();
            completedResult=true;
            audit=timing.snapshot();
            writeTiming(audit,folder);
            % Preserve raw completed observations before enforcing the
            % stricter diagnostic completeness gate below.
            raw=fullfile(folder,'raw');
            [row,~]=csr.validation.exportResearchCase(result,raw,root,snapshot, ...
                fullfile(root,item.ScenarioFile));
            [performance,applications]=csr.analysis.performanceSummary(result);
            analysis=fullfile(folder,'analysis'); mkdir(analysis);
            writetable(stableText(struct2table(performance,'AsArray',true)), ...
                fullfile(analysis,'performance_summary.csv'));
            writetable(stableText(applications),fullfile(analysis,'applications.csv'));
            options=struct('Scenario',item.Scenario,'BucketWidthSeconds',item.BucketWidthSeconds, ...
                'SourceFile','raw/protocol_trace.csv', ...
                'SourceFileSHA256',csr.validation.Artifacts.sha256(fullfile(raw,'protocol_trace.csv')), ...
                'ScenarioSHA256',item.ScenarioSHA256,'ProfileID',item.ProfileId, ...
                'SourceSnapshotSHA256',sourceHash);
            [series,provenance]=csr.analysis.benchmarkAggregates(result,options);
            aggregates=fullfile(analysis,'aggregates.csv');
            writetable(stableText(series),aggregates);
            provenance.output=struct('path','analysis/aggregates.csv', ...
                'sha256',csr.validation.Artifacts.sha256(aggregates));
            csr.validation.Artifacts.writeJson(fullfile(analysis,'aggregate_provenance.json'),provenance);
            current=caseChecks(result,item,audit,mode,key,row,performance);
            checks=[checks;current]; %#ok<AGROW>
            writetable(csr.validation.edgeRecordTable(checks,checkTemplate()), ...
                fullfile(outputDirectory,'checks.csv'));
            performance.Mode=mode; performance.PolicyKey=key;
            performance.CaseId=item.CaseId; performance.NativeCaseId=item.NativeCaseId;
            performance.StorageKey=item.StorageKey;
            performance.Attempts=sum(result.ApplicationAdmissionStatistics.Attempts);
            performance.AdmissionBlocked=performance.Attempts-performance.Generated;
            performance.OmittedApplicationAdmissionRecords=result.Statistics.OmittedApplicationAdmissionRecords;
            summaries{end+1,1}=performance; %#ok<AGROW>
            writetable(csr.validation.edgeRecordTable(vertcat(summaries{:}),summaries{1}), ...
                fullfile(outputDirectory,'summary.csv'));
            inventory=csr.validation.Artifacts.fileInventory(folder);
            local=endsWith({inventory.path},'.mat');
            manifest=struct('schema','csr-tranche16-network-case-v1','status','completed', ...
                'case_id',item.CaseId,'native_case_id',item.NativeCaseId,'storage_key',item.StorageKey, ...
                'mode',mode,'policy_key',key,'base_case_id',item.BaseCaseId, ...
                'scenario',item.Scenario,'scenario_sha256',item.ScenarioSHA256, ...
                'profile_id',item.ProfileId,'seed',item.Seed,'duration_s',item.DurationSeconds, ...
                'bucket_width_s',item.BucketWidthSeconds,'reference_directory',item.ReferenceDirectory, ...
                'source_snapshot_sha256',sourceHash,'ns3_source_commit',plan.ns3_source_commit, ...
                'timing_diagnostics',rmfield(audit,'Records'), ...
                'observer_diagnostics',result.LinkDiagnostics, ...
                'service_diagnostics',result.ServiceDiagnostics, ...
                'structural_check_count',numel(current), ...
                'structural_checks_passed',all([current.Passed]), ...
                'data_drained',row.DataDrained,'numerical_parity_established',false, ...
                'runtime',result.Metadata,'files',inventory(~local),'local_files',inventory(local));
            csr.validation.Artifacts.writeJson(fullfile(folder,'case.json'),manifest);
            entry=struct('CaseId',item.CaseId,'NativeCaseId',item.NativeCaseId, ...
                'Mode',mode,'PolicyKey',key,'Directory',relative, ...
                'ManifestSHA256',csr.validation.Artifacts.sha256(fullfile(folder,'case.json')), ...
                'Passed',all([current.Passed]),'DurationSeconds',item.DurationSeconds, ...
                'RuntimeSeconds',result.Metadata.RuntimeSeconds);
            if isempty(report.Cases), report.Cases=entry; else, report.Cases(end+1,1)=entry; end
            report.CaseCount=numel(report.Cases);
            report.SimulatedSecondsCompleted=report.SimulatedSecondsCompleted+item.DurationSeconds;
            report.CheckpointCount=numel(checks); report.FailedCount=sum(~[checks.Passed]);
            writeReport();
            observer.assertComplete();
            if ~all([current.Passed]), error('csr:t16:Structural','A structural check failed for %s/%s.',key,item.CaseId); end
            elapsed=toc(started);
            remaining=elapsed/report.SimulatedSecondsCompleted* ...
                (report.PlannedSimulatedSeconds-report.SimulatedSecondsCompleted);
            fprintf('  %.1f wall seconds: %d admitted, %d delivered, %d dropped, %d pending.\n', ...
                result.Metadata.RuntimeSeconds,row.Generated,row.Received,row.Dropped,row.Pending);
            fprintf('  Total elapsed %.1f minutes; rough remaining %.1f minutes from observed speed.\n', ...
                elapsed/60,remaining/60);
            clear simulation result observer timing audit;
        catch failure
            % researchSummary can reject a fully executed simulation before
            % exportResearchCase writes raw files. Retain its observations
            % without converting that structural failure into a success.
            if completedResult
                try
                    csr.analysis.exportResults(result,fullfile(folder,'raw'));
                catch exportFailure
                    % Keep at least the completed counters if an individual
                    % table or filesystem error also prevents standard export.
                    try
                        partial=struct('Schema','csr-tranche16-partial-result-v1', ...
                            'Metadata',result.Metadata,'Statistics',result.Statistics, ...
                            'ExportFailure',struct('Identifier',exportFailure.identifier, ...
                            'Message',exportFailure.message));
                        csr.validation.Artifacts.writeJson(fullfile(folder,'partial.json'),partial);
                    catch
                        % The original simulation/structural failure remains
                        % authoritative even if the output device also fails.
                    end
                end
            end
            if exist('timing','var')
                try, writeTiming(timing.snapshot(),folder); catch, end %#ok<CTCH>
            end
            report.Failure=struct('Identifier',failure.identifier,'Message',failure.message, ...
                'CaseId',item.CaseId,'PolicyKey',key,'Stack',failure.stack);
            csr.validation.Artifacts.writeJson(fullfile(folder,'failure.json'),report.Failure);
            writeReport(); rethrow(failure);
        end
    end
end
report.DiagnosticCompleted=report.CaseCount==12 && report.CheckpointCount==192 && ...
    report.SimulatedSecondsCompleted==9360;
report.Passed=report.DiagnosticCompleted && report.FailedCount==0 && all([report.Cases.Passed]);
report.ElapsedSeconds=toc(started); writeReport();
    function writeReport()
        csr.validation.Artifacts.writeJson(fullfile(outputDirectory,'summary.json'),report);
    end
end

function records=caseChecks(result,item,audit,mode,key,row,performance)
r=audit.Records; s=result.Statistics;
names={'Ordinal','SourceId','ReceiverId','FrameId','TxSeconds','PropagationSeconds', ...
    'DurationSeconds','PreambleSeconds','PhysicalStartSeconds','PhysicalPreambleEndSeconds', ...
    'PhysicalEndSeconds','StartSeconds','PreambleEndSeconds','EndSeconds', ...
    'TxNanoseconds','PropagationNanoseconds','DurationNanoseconds','PreambleNanoseconds', ...
    'StartNanoseconds','PreambleEndNanoseconds','EndNanoseconds','StartShiftSeconds', ...
    'PreambleEndShiftSeconds','EndShiftSeconds'};
schema=istable(r) && isequal(r.Properties.VariableNames,names) && ...
    isa(r.Ordinal,'uint64') && isa(r.FrameId,'uint64');
if ~schema, error('csr:t16:TimingSchema','Timing audit column identities or integer types differ.'); end
floating=setdiff(names,{'Ordinal','FrameId'},'stable'); values=r{:,floating};
finite=all(isfinite(values(:)));
causal=all(r.StartSeconds>=r.TxSeconds & r.PreambleEndSeconds>=r.StartSeconds & ...
    r.EndSeconds>=r.PreambleEndSeconds & r.EndSeconds>r.StartSeconds);
physical=isequal(r.PhysicalStartSeconds,r.TxSeconds+r.PropagationSeconds) && ...
    isequal(r.PhysicalPreambleEndSeconds,r.TxSeconds+r.PropagationSeconds+r.PreambleSeconds) && ...
    isequal(r.PhysicalEndSeconds,r.TxSeconds+r.PropagationSeconds+r.DurationSeconds);
components=round([r.TxSeconds r.PropagationSeconds r.DurationSeconds r.PreambleSeconds]*1e9);
rounded=isequal(components,[r.TxNanoseconds r.PropagationNanoseconds r.DurationNanoseconds r.PreambleNanoseconds]) && ...
    isequal(r.StartNanoseconds,r.TxNanoseconds+r.PropagationNanoseconds) && ...
    isequal(r.PreambleEndNanoseconds,r.StartNanoseconds+r.PreambleNanoseconds) && ...
    isequal(r.EndNanoseconds,r.StartNanoseconds+r.DurationNanoseconds);
if strcmp(mode,'continuous')
    selected=isequal(r.StartSeconds,r.PhysicalStartSeconds) && ...
        isequal(r.PreambleEndSeconds,r.PhysicalPreambleEndSeconds) && isequal(r.EndSeconds,r.PhysicalEndSeconds);
else
    selected=isequal(r.StartSeconds,r.StartNanoseconds/1e9) && ...
        isequal(r.PreambleEndSeconds,r.PreambleEndNanoseconds/1e9) && isequal(r.EndSeconds,r.EndNanoseconds/1e9);
end
shifts=[r.StartShiftSeconds r.PreambleEndShiftSeconds r.EndShiftSeconds];
actual=[r.StartSeconds-r.PhysicalStartSeconds r.PreambleEndSeconds-r.PhysicalPreambleEndSeconds ...
    r.EndSeconds-r.PhysicalEndSeconds];
bound=1.5e-9+8*eps(max([1;r.PhysicalEndSeconds]));
shiftValid=isequal(shifts,actual) && all(abs(shifts(:))<=bound) && ...
    audit.MaxAbsShiftSeconds==max([0;abs(shifts(:))]);
coverage=audit.Omitted==0 && audit.Count==height(r) && audit.Count>0 && ...
    audit.Count==s.PhysicalAttempts && audit.Count==s.PhysicalTransmissions*(numel(item.Config.Nodes)-1) && ...
    audit.MaxRecords==100000 && audit.Count<=audit.MaxRecords && ...
    isequal(r.Ordinal,uint64((1:height(r))')) && all(r.SourceId~=r.ReceiverId);
identity=isequaln(result.Config,item.Config) && strcmp(result.Config.Channel.Model,'csr-phy') && ...
    strcmp(result.Metadata.Backend,'portable') && result.Config.Seed==item.Seed && ...
    result.Config.DurationSeconds==item.DurationSeconds && ...
    strcmp(result.Config.SharedScenario.SourceSHA256,item.ScenarioSHA256);
labels={'research_accounting','performance_accounting','complete_protocol_trace', ...
    'complete_phy_trace','complete_admission_trace','complete_feedback_trace', ...
    'complete_service_trace','timing_mode','timing_coverage','timing_schema', ...
    'finite_timing','causal_callbacks','physical_operands','timing_policy', ...
    'timing_shift_bound','scenario_identity'};
passed=[row.StructuralChecksPassed,performance.StructuralChecksPassed, ...
    s.OmittedTraceRecords==0,s.OmittedPhyTraceRecords==0, ...
    s.OmittedApplicationAdmissionRecords==0,result.LinkDiagnostics.Complete, ...
    result.ServiceDiagnostics.Complete,strcmp(audit.Mode,mode),coverage,schema, ...
    finite,causal,physical,rounded && selected,shiftValid,identity];
records=repmat(checkTemplate(),numel(labels),1);
for k=1:numel(labels)
    records(k)=struct('PolicyKey',key,'CaseId',item.CaseId,'Check',labels{k},'Passed',logical(passed(k)));
end
end

function row=checkTemplate()
row=struct('PolicyKey','','CaseId','','Check','','Passed',false);
end

function writeTiming(audit,folder)
records=audit.Records; names=records.Properties.VariableNames;
for k=1:numel(names)
    name=names{k};
    if endsWith(name,'Seconds')
        values=records.(name);
        records.([name 'Decimal'])=compose('%.17g',values);
        records.([name 'Hex'])=string(cellstr(num2hex(values)));
    end
end
writetable(records,fullfile(folder,'timing.csv'));
metadata=rmfield(audit,'Records');
metadata.Schema='csr-tranche16-transport-audit-v1';
csr.validation.Artifacts.writeJson(fullfile(folder,'timing.json'),metadata);
end

function value=stableText(value)
% One scalar string per text row, including equal-width case labels.
names=value.Properties.VariableNames;
for k=1:numel(names)
    column=value.(names{k});
    if ischar(column), value.(names{k})=string(cellstr(column));
    elseif iscellstr(column), value.(names{k})=string(column); end %#ok<ISCLSTR>
end
end
