function report = requireAvailable()
%REQUIREAVAILABLE Gate optional R2026a APIs before loading native subclasses.
% Symbol presence is necessary but does not certify license or execution.
report = csr.sim.capabilities();
if ~report.HasWirelessNetworkSimulator || ~report.HasWnetNode || ...
        ~report.HasWirelessPacket
    error('csr:sim:NativeUnavailable', ...
        ['The wireless-clock backend requires R2026a Wireless Network ' ...
        'Toolbox with wirelessNetworkSimulator, wnet.Node, and wirelessPacket. ' ...
        'Use Backend = ''portable'' on this installation.']);
end
end
