function report = relayServiceContract(outputDirectory,root,snapshot,sourceSnapshotSHA256)
%RELAYSERVICECONTRACT Passive real-network service/admission diagnosis.
% Existing observer only, retaining its six public MAC scalar reads per
% cancellation snapshot. No new HOP/NWK polling, timer, receiver timing,
% post-stop drain or delivery target is added to the simulation.
[cases,plan]=csr.scenario.tranche18Suite();
if isfolder(outputDirectory)
    error('csr:t18:OutputExists','Use a new directory; diagnostic runs cannot resume partial simulations.');
end
mkdir(outputDirectory);
report=struct('Schema','csr-tranche18-relay-service-contract-v1', ...
    'DiagnosticCompleted',false,'Completed',false,'Passed',false,'CaseCount',0, ...
    'ObservedCaseCount',0,'ControlCaseCount',0,'PlannedCaseCount',11, ...
    'CheckpointCount',0,'FailedCount',0,'SimulatedSecondsCompleted',0, ...
    'PlannedSimulatedSeconds',6900,'SourceSnapshotSHA256',sourceSnapshotSHA256, ...
    'PlanSHA256',csr.validation.Artifacts.sha256(fullfile(root,'scenarios','t18','plan.json')), ...
    'Runtime',csr.sim.capabilities(),'NonperturbationPassed',false, ...
    'NumericalParityEstablished',false,'FullAcceptanceEstablished',false, ...
    'Cases',struct([]),'Scope',['Real-PHY autonomous routing: three reduced traffic conditions, ' ...
        'three seeds, one original campus prefix, and one identical observer-off control. ' ...
        'Direct callback observations support offline cohort analysis; no hidden queue-state claims.']);
checks=repmat(checkTemplate(),0,1); summaries=cell(0,1);
started=tic; writeReport();
order=cellstr(string(plan.execution_order));
for k=1:numel(order)
    key=order{k}; observed=~strcmp(key,'m128_off'); nativeKey=key;
    if ~observed, nativeKey='m128'; end
    item=cases(strcmp({cases.CaseId},nativeKey));
    folder=fullfile(outputDirectory,key); mkdir(folder);
    completedResult=false;
    fprintf('\nRelay service %d/%d: %s (%g simulated seconds), observer %d.\n', ...
        k,numel(order),key,item.DurationSeconds,observed);
    fprintf('Started UTC %s. Progress is printed between cases; no simulation callbacks are added.\n', ...
        csr.validation.Artifacts.utcNow());
    try
        if observed
            observer=csr.sim.AckServiceDiagnostics(item.ObserverMaxRecords,item.ServiceWindowSeconds);
            simulation=csr.sim.NetworkSimulation(item.Config,observer);
        else
            simulation=csr.sim.NetworkSimulation(item.Config);
        end
        result=simulation.run(); completedResult=true;
        raw=fullfile(folder,'raw');
        [row,~]=csr.validation.exportResearchCase(result,raw,root,snapshot, ...
            fullfile(root,item.ScenarioFile));
        [performance,applications]=csr.analysis.performanceSummary(result);
        analysis=fullfile(folder,'analysis'); mkdir(analysis);
        writetable(stableText(struct2table(performance,'AsArray',true)), ...
            fullfile(analysis,'performance_summary.csv'));
        writetable(stableText(applications),fullfile(analysis,'applications.csv'));
        options=struct('Scenario',item.Scenario,'BucketWidthSeconds',item.BucketWidthSeconds, ...
            'SourceFile','raw/protocol_trace.csv', ...
            'SourceFileSHA256',csr.validation.Artifacts.sha256(fullfile(raw,'protocol_trace.csv')), ...
            'ScenarioSHA256',item.ScenarioSHA256,'ProfileID',item.ProfileId, ...
            'SourceSnapshotSHA256',sourceSnapshotSHA256);
        [series,provenance]=csr.analysis.benchmarkAggregates(result,options);
        aggregatePath=fullfile(analysis,'aggregates.csv');
        writetable(stableText(series),aggregatePath);
        provenance.output=struct('path','analysis/aggregates.csv', ...
            'sha256',csr.validation.Artifacts.sha256(aggregatePath));
        csr.validation.Artifacts.writeJson(fullfile(analysis,'aggregate_provenance.json'),provenance);
        current=caseChecks(result,item,key,observed,simulation.Scheduler.Now,row,performance);
        checks=[checks;current]; %#ok<AGROW>
        writetable(csr.validation.edgeRecordTable(checks,checkTemplate()),fullfile(outputDirectory,'checks.csv'));
        performance.CaseId=key; performance.NativeCaseId=nativeKey;
        performance.Condition=item.Condition; performance.ObserverEnabled=observed;
        performance.Attempts=sum(result.ApplicationAdmissionStatistics.Attempts);
        performance.AdmissionBlocked=performance.Attempts-performance.Generated;
        performance.OmittedApplicationAdmissionRecords=result.Statistics.OmittedApplicationAdmissionRecords;
        summaries{end+1,1}=performance; %#ok<AGROW>
        writetable(csr.validation.edgeRecordTable(vertcat(summaries{:}),summaries{1}), ...
            fullfile(outputDirectory,'summary.csv'));
        files=csr.validation.Artifacts.fileInventory(folder);
        local=endsWith({files.path},'.mat');
        manifest=struct('schema','csr-tranche18-relay-service-case-v1','status','completed', ...
            'case_id',key,'native_case_id',nativeKey,'base_case_id',nativeKey,'storage_key',key, ...
            'condition',item.Condition,'case',item.PlanEntry,'scenario',item.Scenario, ...
            'scenario_sha256',item.ScenarioSHA256,'profile_id',item.ProfileId, ...
            'seed',item.Seed,'duration_s',item.DurationSeconds,'scheduler_stop_s',simulation.Scheduler.Now, ...
            'bucket_width_s',item.BucketWidthSeconds,'reference_directory',item.ReferenceDirectory, ...
            'mode','continuous','receiver_timing_injected',false,'observer_enabled',observed, ...
            'source_snapshot_sha256',sourceSnapshotSHA256,'source_files',snapshot, ...
            'ns3_source_commit',plan.ns3_source_commit,'runtime',result.Metadata, ...
            'structural_check_count',numel(current),'structural_checks_passed',all([current.Passed]), ...
            'data_drained',row.DataDrained,'numerical_parity_established',false, ...
            'observer_diagnostics',struct(),'service_diagnostics',struct(), ...
            'files',files(~local),'local_files',files(local));
        if observed
            manifest.observer_diagnostics=result.LinkDiagnostics;
            manifest.service_diagnostics=result.ServiceDiagnostics;
        end
        casePath=fullfile(folder,'case.json');
        csr.validation.Artifacts.writeJson(casePath,manifest);
        entry=struct('CaseId',key,'NativeCaseId',nativeKey,'Directory',key, ...
            'ManifestSHA256',csr.validation.Artifacts.sha256(casePath), ...
            'ObserverEnabled',observed,'Passed',all([current.Passed]), ...
            'DurationSeconds',item.DurationSeconds,'RuntimeSeconds',result.Metadata.RuntimeSeconds);
        if isempty(report.Cases), report.Cases=entry; else, report.Cases(end+1,1)=entry; end
        report.CaseCount=numel(report.Cases);
        report.ObservedCaseCount=report.ObservedCaseCount+double(observed);
        report.ControlCaseCount=report.ControlCaseCount+double(~observed);
        report.SimulatedSecondsCompleted=report.SimulatedSecondsCompleted+item.DurationSeconds;
        report.CheckpointCount=numel(checks); report.FailedCount=sum(~[checks.Passed]);
        writeReport();
        if observed, observer.assertComplete(); end
        if ~all([current.Passed])
            error('csr:t18:Structural','A structural check failed for %s.',key);
        end
        if strcmp(key,'m128_off')
            comparison=nonperturbation(outputDirectory);
            csr.validation.Artifacts.writeJson(fullfile(outputDirectory,'nonperturbation.json'),comparison);
            report.NonperturbationPassed=comparison.Passed;
            writeReport();
            if ~comparison.Passed
                error('csr:t18:Nonperturbation','The passive observer changed a core result or exported trace.');
            end
        end
        elapsed=toc(started);
        remaining=elapsed/report.SimulatedSecondsCompleted* ...
            (report.PlannedSimulatedSeconds-report.SimulatedSecondsCompleted);
        fprintf('  %.1f wall seconds: %d admitted, %d delivered, %d dropped, %d pending.\n', ...
            result.Metadata.RuntimeSeconds,row.Generated,row.Received,row.Dropped,row.Pending);
        fprintf('  Elapsed %.1f min; rough remaining %.1f min (case complexity differs).\n',elapsed/60,remaining/60);
        clear simulation result observer;
    catch failure
        if completedResult
            try
                if ~isfile(fullfile(folder,'raw','summary.json'))
                    csr.analysis.exportResults(result,fullfile(folder,'raw'));
                end
            catch exportFailure
                try
                    csr.validation.Artifacts.writeJson(fullfile(folder,'partial.json'), ...
                        struct('Schema','csr-tranche18-partial-result-v1', ...
                        'Metadata',result.Metadata,'Statistics',result.Statistics, ...
                        'ExportFailure',struct('Identifier',exportFailure.identifier,'Message',exportFailure.message)));
                catch
                    % Preserve the original failure even if the output device failed.
                end
            end
        end
        report.Failure=struct('Identifier',failure.identifier,'Message',failure.message, ...
            'CaseId',key,'Stack',failure.stack);
        csr.validation.Artifacts.writeJson(fullfile(folder,'failure.json'),report.Failure);
        writeReport(); rethrow(failure);
    end
end
csr.validation.Artifacts.checkSnapshot(root,snapshot);
report.DiagnosticCompleted=report.CaseCount==11 && report.ObservedCaseCount==10 && ...
    report.ControlCaseCount==1 && report.CheckpointCount==132 && report.SimulatedSecondsCompleted==6900;
report.Completed=report.DiagnosticCompleted;
report.Passed=report.DiagnosticCompleted && report.FailedCount==0 && report.NonperturbationPassed;
report.ElapsedSeconds=toc(started); writeReport();
    function writeReport()
        csr.validation.Artifacts.writeJson(fullfile(outputDirectory,'summary.json'),report);
    end
end

function records=caseChecks(result,item,key,observed,stop,row,performance)
s=result.Statistics;
feedback=~any(isfield(result,{'LinkDiagnostics','LinkDecisionTrace','ActualFeedbackTrace'}));
service=~any(isfield(result,{'ServiceDiagnostics','ServiceTrace'})); cancellation=service;
if observed
    d=result.LinkDiagnostics; a=result.ServiceDiagnostics;
    feedback=d.Complete && d.MaxRecords==item.ObserverMaxRecords && ...
        d.OmittedDecisionRecords==0 && d.OmittedActualFeedbackRecords==0 && ...
        d.UnmatchedActualFeedbackRecords==0 && d.CorrelationErrors==0;
    service=a.Complete && a.MaxRecords==item.ObserverMaxRecords && ...
        a.OmittedServiceRecords==0 && a.OutOfWindowServiceEvents==0 && ...
        a.WindowStartSeconds==0 && a.WindowEndSeconds==item.DurationSeconds+1 && ...
        a.ServiceEventCount==height(result.ServiceTrace);
    cancellation=a.CancellationPairsComplete && a.CancellationPairErrors==0 && ...
        ~a.PendingCancellationPair && a.CancellationBeforeCount==a.CancellationAfterCount;
end
times=[result.ProtocolTrace.TimeSeconds;result.PhyTrace.TimeSeconds; ...
    result.ApplicationAdmissionTrace.TimeSeconds];
ordered=all(diff(result.ProtocolTrace.TimeSeconds)>=0) && ...
    all(diff(result.PhyTrace.TimeSeconds)>=0) && ...
    all(diff(result.ApplicationAdmissionTrace.TimeSeconds)>=0);
if observed
    times=[times;result.ServiceTrace.TimeSeconds]; %#ok<AGROW>
    ordered=ordered && all(diff(result.ServiceTrace.TimeSeconds)>=0);
end
labels={'research_accounting','performance_accounting','complete_protocol_trace', ...
    'complete_phy_trace','complete_admission_trace','observer_feedback_contract', ...
    'observer_service_contract','cancellation_contract','default_continuous_timing', ...
    'scenario_identity','completed_horizon','trace_horizon'};
passed=[row.StructuralChecksPassed,performance.StructuralChecksPassed, ...
    s.OmittedTraceRecords==0,s.OmittedPhyTraceRecords==0, ...
    s.OmittedApplicationAdmissionRecords==0 && ...
        height(result.ApplicationAdmissionTrace)==sum(result.ApplicationAdmissionStatistics.Attempts), ...
    feedback,service,cancellation,~isfield(result,'TransportTiming'), ...
    isequaln(result.Config,item.Config) && strcmp(result.Metadata.Backend,'portable') && ...
        strcmp(result.Metadata.ChannelModel,'csr-phy') && ...
        strcmp(result.Metadata.ModelStage,'tranche-3-autonomous-network-routing'), ...
    stop==item.DurationSeconds,ordered && all(isfinite(times) & times>=0 & times<=item.DurationSeconds)];
records=repmat(checkTemplate(),numel(labels),1);
for k=1:numel(labels)
    records(k)=struct('CaseId',key,'Check',labels{k},'Passed',logical(passed(k)));
end
end

function comparison=nonperturbation(directory)
left=fullfile(directory,'m128','raw'); right=fullfile(directory,'m128_off','raw');
on=jsondecode(fileread(fullfile(left,'summary.json')));
off=jsondecode(fileread(fullfile(right,'summary.json')));
names={'trace.csv','protocol_trace.csv','phy_trace.csv','application_admission_trace.csv', ...
    'application_admission_statistics.csv','nodes.csv','mac_nodes.csv','hop_nodes.csv', ...
    'nwk_nodes.csv','routes.csv','neighbors.csv','scenario.csv'};
files=repmat(struct('Path','','ObservedSHA256','','ControlSHA256','','Equal',false),numel(names),1);
for k=1:numel(names)
    a=csr.validation.Artifacts.sha256(fullfile(left,names{k}));
    b=csr.validation.Artifacts.sha256(fullfile(right,names{k}));
    files(k)=struct('Path',names{k},'ObservedSHA256',a,'ControlSHA256',b,'Equal',strcmp(a,b));
end
onMetadata=rmfield(on.Metadata,'RuntimeSeconds');
offMetadata=rmfield(off.Metadata,'RuntimeSeconds');
comparison=struct('Schema','csr-tranche18-observer-nonperturbation-v1', ...
    'ObserverOnCase','m128','ObserverOffCase','m128_off', ...
    'StatisticsEqual',isequaln(on.Statistics,off.Statistics), ...
    'ConfigurationEqual',isequaln(on.Config,off.Config), ...
    'MetadataEqualExcludingRuntimeSeconds',isequaln(onMetadata,offMetadata), ...
    'MetadataExcludedFields',{{'RuntimeSeconds'}},'Files',files, ...
    'ObservedSummarySHA256',csr.validation.Artifacts.sha256(fullfile(left,'summary.json')), ...
    'ControlSummarySHA256',csr.validation.Artifacts.sha256(fullfile(right,'summary.json')), ...
    'Passed',false);
comparison.Passed=comparison.StatisticsEqual && comparison.ConfigurationEqual && ...
    comparison.MetadataEqualExcludingRuntimeSeconds && all([files.Equal]);
end

function row=checkTemplate()
row=struct('CaseId','','Check','','Passed',false);
end

function value=stableText(value)
for name=value.Properties.VariableNames
    column=value.(name{1});
    if ischar(column), value.(name{1})=string(cellstr(column));
    elseif iscellstr(column), value.(name{1})=string(column); end %#ok<ISCLSTR>
end
end
