function frame = packet(id, flow, generatedSeconds, radio)
%PACKET Logical frame for controlled transport; wire serialization is deferred.
% Source bare DATA payload: 17 MAC + 8 HOP + 7 NWK bytes (app + 32).
% This does not copy ns-3's compact CsrHeader storage envelope.
frame = struct('Id', id, 'SourceId', flow.SourceId, ...
    'DestinationId', flow.DestinationId, 'GeneratedSeconds', generatedSeconds, ...
    'ApplicationPayloadBytes', flow.ApplicationPayloadBytes, ...
    'WirePayloadBytes', flow.ApplicationPayloadBytes + 32, ...
    'RateKeyKbps', radio.RateKeyKbps, 'Preamble', radio.Preamble);
end
