classdef RadioProfile
    %RADIOPROFILE Release-independent CSR radio configuration.
    %   Values and names follow CsrPhyProfile in ns-3 csr-phy-model.h at
    %   486d9e0. ClosureDelegate is an optional MATLAB visibility function
    %   accepting (distanceMeters, txHeightMeters, rxHeightMeters).

    methods (Static)
        function profile = defaults()
            profile = struct( ...
                'TxPowerDbm', 0, ...
                'NoiseFloorDbm', -106.975, ...
                'NoiseReferenceBwHz', 1e6, ...
                'ScaleNoiseWithBandwidth', true, ...
                'TxBaseFrequencyHz', 30e6, ...
                'RxBaseFrequencyHz', 30e6, ...
                'TxBwHz', 1e6, 'RxBwHz', 1e6, ...
                'TxAntennaGainDb', 0, 'RxAntennaGainDb', 0, ...
                'TxHeightMeters', 1, 'RxHeightMeters', 1, ...
                'SyncSnrThresholdDb', -11, ...
                'SyncSnrThresholdVarianceDb2', 0.25, ...
                'StochasticSyncThreshold', true, ...
                'EccThreshold', 0.1, ...
                'ClosureMode', 'EARTH_LINE_OF_SIGHT', ...
                'EarthRadiusMeters', 6371000, ...
                'PropagationModel', 'OPNET_THREE_PATH', ...
                'RefLossDb', 60, 'PathlossExp', 2, 'DistanceScale', 1, ...
                'ClosureDelegate', []);
        end

        function profile = validate(candidate)
            % Fill omitted fields; reject typos rather than ignore them.
            if ~isstruct(candidate) || ~isscalar(candidate)
                error('csr:phy:InvalidRadioProfile', ...
                    'Radio profile must be a scalar struct.');
            end
            profile = csr.phy.RadioProfile.defaults();
            names = fieldnames(candidate);
            for k = 1:numel(names)
                name = names{k};
                if ~isfield(profile, name)
                    error('csr:phy:UnknownRadioAttribute', ...
                        'Unknown CSR radio attribute "%s".', name);
                end
                profile.(name) = candidate.(name);
            end
            positive = {'NoiseReferenceBwHz', 'TxBaseFrequencyHz', ...
                'RxBaseFrequencyHz', 'TxBwHz', 'RxBwHz', ...
                'EarthRadiusMeters', 'DistanceScale'};
            nonnegative = {'TxHeightMeters', 'RxHeightMeters', ...
                'SyncSnrThresholdVarianceDb2', 'PathlossExp'};
            unrestricted = {'TxPowerDbm', 'NoiseFloorDbm', ...
                'TxAntennaGainDb', 'RxAntennaGainDb', ...
                'SyncSnrThresholdDb', 'RefLossDb', 'EccThreshold'};
            allNumeric = [positive, nonnegative, unrestricted];
            for k = 1:numel(allNumeric)
                name = allNumeric{k};
                value = profile.(name);
                if ~isnumeric(value) || ~isscalar(value) || ...
                        ~isreal(value) || ~isfinite(value)
                    error('csr:phy:InvalidRadioProfile', ...
                        'Radio attribute %s must be a finite real scalar.', name);
                end
                profile.(name) = double(value);
            end
            for k = 1:numel(positive)
                if profile.(positive{k}) <= 0
                    error('csr:phy:InvalidRadioProfile', ...
                        'Radio attribute %s must be positive.', positive{k});
                end
            end
            for k = 1:numel(nonnegative)
                if profile.(nonnegative{k}) < 0
                    error('csr:phy:InvalidRadioProfile', ...
                        'Radio attribute %s must be nonnegative.', nonnegative{k});
                end
            end
            if profile.EccThreshold < 0 || profile.EccThreshold > 1 || ...
                    ~isfinite(profile.TxBaseFrequencyHz + profile.TxBwHz) || ...
                    ~isfinite(profile.RxBaseFrequencyHz + profile.RxBwHz)
                error('csr:phy:InvalidRadioProfile', ...
                    'ECC threshold must be in [0,1] and passband edges finite.');
            end
            flags = {'ScaleNoiseWithBandwidth', 'StochasticSyncThreshold'};
            for k = 1:numel(flags)
                value = profile.(flags{k});
                if ~islogical(value) || ~isscalar(value)
                    error('csr:phy:InvalidRadioProfile', ...
                        'Radio attribute %s must be a scalar logical.', flags{k});
                end
            end
            profile.ClosureMode = csr.phy.RadioProfile.choice( ...
                profile.ClosureMode, ...
                {'NEVER_OCCLUDED', 'EARTH_LINE_OF_SIGHT', 'DELEGATE'}, ...
                'ClosureMode');
            profile.PropagationModel = csr.phy.RadioProfile.choice( ...
                profile.PropagationModel, {'OPNET_THREE_PATH', 'LOG_DISTANCE'}, ...
                'PropagationModel');
            if ~isempty(profile.ClosureDelegate) && ...
                    ~isa(profile.ClosureDelegate, 'function_handle')
                error('csr:phy:InvalidRadioProfile', ...
                    'ClosureDelegate must be empty or a function handle.');
            end
        end
    end

    methods (Static, Access = private)
        function value = choice(value, options, name)
            if isstring(value) && isscalar(value)
                value = char(value);
            end
            if ~ischar(value) || ~isrow(value) || ...
                    ~any(strcmp(value, options))
                error('csr:phy:InvalidRadioProfile', ...
                    'Invalid %s; allowed values: %s.', name, strjoin(options, ', '));
            end
        end
    end
end
