function report=run_source5_receiver_replay(runtimeRoot,boundDir,outputDir)
%RUN_SOURCE5_RECEIVER_REPLAY Replay native seed-132 node-4 ACK contention.
% Requires the fresh native capture bound by bind_capture.py, plus the
% candidate +csr tree. This never mutates production source or native inputs.
if nargin<3, outputDir=''; end
local=fileparts(mfilename('fullpath'));
fixture=fullfile(local,'fixture');
shared=fullfile(local,'..','discovery_replay');
if ~isfolder(fullfile(runtimeRoot,'+csr')) || ~isfolder(shared)
    error('source5_receiver:Paths','Supply candidate +csr tree and two-case package.');
end
if ~isfolder(boundDir) || ~isfile(fullfile(boundDir,'manifest.json'))
    error('source5_receiver:Capture','Run bind_capture.py on verified native capture first.');
end
addpath(runtimeRoot);
addpath(shared);
native=jsondecode(fileread(fullfile(fixture,'manifest.json')));
bound=jsondecode(fileread(fullfile(boundDir,'manifest.json')));
seam=jsondecode(fileread(fullfile(shared,'seam_manifest.json')));
if ~strcmp(native.schema,'csr-source5-node4-rx-observed-v1') || ...
        ~strcmp(bound.schema,'csr-source5-node4-rx-bound-v1') || ...
        ~strcmp(bound.status,'native_capture_bound') || ...
        ~isfield(bound,'receiver_input_semantics') || ...
        ~strcmp(bound.receiver_input_semantics,'actual_mac_idle_search_transitions_v2') || ...
        ~isequal(double(bound.window_ns(:))',[300e9 330e9]) || ...
        ~isequal(double(native.window_ns(:))',[300e9 330e9]) || ...
        ~bound.clean_boundary_at_300s || ...
        ~strcmp(bound.native_prefix_sha256,native.native_prefix_sha256) || ...
        ~strcmp(bound.fixture_manifest_sha256, ...
        csr.validation.Artifacts.sha256(fullfile(fixture,'manifest.json')))
    error('source5_receiver:Binding','Unknown or altered native capture/fixture binding.');
end
if ~strcmp(seam.production_signal_engine_sha256, ...
        '289c764bac0de95fefa75812e1b5090dcdf1953e35960cf7f02c4e298f4e294e') || ...
        ~strcmp(csr.validation.Artifacts.sha256(fullfile(runtimeRoot, ...
        '+csr','+phy','SignalEngine.m')),seam.production_signal_engine_sha256) || ...
        ~strcmp(csr.validation.Artifacts.sha256(fullfile(shared,'DiscoverySignalEngine.m')), ...
        seam.generated_signal_engine_sha256)
    error('source5_receiver:SeamBinding', ...
        'Production receiver or validation-only draw seam changed; re-audit.');
end
for name={"tx.csv","expected.csv","scenario.csv"}
    file=char(name{1});
    key=strrep(file,'.','_');
    actual=csr.validation.Artifacts.sha256(fullfile(fixture,file));
    if ~strcmp(actual,native.fixture_sha256.(key))
        error('source5_receiver:FixtureHash','Changed native fixture: %s.',file);
    end
end
boundFiles={'tx.csv','phy_draws.csv','phy_intervals.csv','receiver_inputs.csv', ...
            'receiver_state_expected.csv','receiver_request_audit.csv', ...
            'tx_children.csv','ack_outcomes.csv'};
for index=1:numel(boundFiles)
    file=boundFiles{index};
    key=strrep(file,'.','_');
    if ~strcmp(csr.validation.Artifacts.sha256(fullfile(boundDir,file)), ...
            bound.files_sha256.(key))
        error('source5_receiver:BoundHash','Changed native capture input: %s.',file);
    end
end
tx=readtable(fullfile(boundDir,'tx.csv'),'TextType','string');
expected=readtable(fullfile(fixture,'expected.csv'),'TextType','string');
states=readtable(fullfile(boundDir,'receiver_inputs.csv'),'TextType','string');
stateExpected=readtable(fullfile(boundDir,'receiver_state_expected.csv'),'TextType','string');
stateRequests=readtable(fullfile(boundDir,'receiver_request_audit.csv'),'TextType','string');
intervals=readtable(fullfile(boundDir,'phy_intervals.csv'),'TextType','string');
acks=readtable(fullfile(boundDir,'ack_outcomes.csv'),'TextType','string');
if height(tx)~=299 || height(expected)~=255 || ...
        height(acks)~=double(bound.ack_child_count) || ...
        height(intervals)~=double(bound.node4_interval_count) || ...
        height(states)~=double(bound.node4_external_state_count) || ...
        height(stateExpected)~=double(bound.node4_state_transition_count) || ...
        height(stateRequests)~=double(bound.node4_refresh_request_count) || ...
        any(stateRequests.replayed_as_input~=0) || ...
        any(states.node~=4) || ...
        any(~ismember(string(states.state),["idle","search"]))
    error('source5_receiver:Coverage','Unbound TX/receiver/child/state history.');
end
scheduler=csr.sim.EventScheduler(500000);
streams=csr.sim.RandomStreams(132);
config=csr.scenario.importNs3(fullfile(fixture,'scenario.csv'), ...
    struct('HistoricalBenchmark',true));
closureCompletionNs=containers.Map('KeyType','double','ValueType','double');
receiverIndex=find([config.Nodes.Id]==4);
if numel(receiverIndex)~=1
    error('source5_receiver:Scenario','Node 4 is absent from bound scenario.');
end
for i=1:height(tx)
    row=tx(i,:);
    if row.node==4, continue; end
    sourceIndex=find([config.Nodes.Id]==double(row.node));
    if numel(sourceIndex)~=1
        error('source5_receiver:Scenario','Unknown native TX node.');
    end
    distance=norm(config.Nodes(sourceIndex).PositionMeters- ...
        config.Nodes(receiverIndex).PositionMeters);
    airtime=csr.phy.airtime(double(row.wire_bytes),double(row.rate_kbps), ...
        char(row.preamble));
    closureCompletionNs(double(row.tx_id))=round((double(row.time_ns)/1e9+ ...
        airtime+distance/config.Channel.PropagationSpeedMps)*1e9);
end
drainUntilSec=max(330,max(cell2mat(values(closureCompletionNs)))/1e9)+1e-6;
config.DurationSeconds=ceil(drainUntilSec);
sampler=Source5ReceiverSampler(fullfile(boundDir,'phy_draws.csv'), ...
    @()scheduler.Now);
observed=repmat(struct('tx_id',0,'receiver',0,'time_ns',0, ...
    'success',false,'reason','','collision_count',0, ...
    'header_errors',0,'payload_errors',0,'total_errors',0),0,1);
observedIntervals=repmat(struct('tx_id',0,'ordinal',0, ...
    'time_ns',0,'start_ns',0,'end_ns',0,'noise_watts',0, ...
    'jsr_db',0,'offset_sec',0,'collisions',0,'same_rate',false),0,1);
observedStates=repmat(struct('time_ns',0,'state_before','','state_after',''),0,1);
lastNode4State='Search';
intervalOrdinals=containers.Map('KeyType','double','ValueType','double');
engine=DiscoverySignalEngine(config,scheduler,streams,@receive,@traceInterval, ...
    @stateChange,[],sampler);
if strcmp(native.initial_node4_state,'idle')
    engine.setReceiverState(4,'Idle');
end
actions=[table(double(tx.time_ns),double(tx.event_order), ...
                repmat("tx",height(tx),1),(1:height(tx))', ...
                'VariableNames',{'time_ns','event_order','kind','index'}); ...
         table(double(states.time_ns),double(states.event_order), ...
                repmat("state",height(states),1),(1:height(states))', ...
                'VariableNames',{'time_ns','event_order','kind','index'})];
actions=sortrows(actions,{'time_ns','event_order'});
if any(actions.time_ns<300e9 | actions.time_ns>=330e9)
    error('source5_receiver:Window','Replay event outside [300,330).');
end
if any(ismember(states.time_ns,tx.time_ns))
    error('source5_receiver:Tie','Unresolved cross-stream TX/receiver-state tie.');
end
for i=1:height(actions)
    when=actions.time_ns(i)/1e9;
    if actions.kind(i)=="tx"
        item=tx(actions.index(i),:);
        scheduler.scheduleAt(when,@()transmit(item));
    else
        item=states(actions.index(i),:);
        scheduler.scheduleAt(when,@()externalState(item));
    end
end
problemId=''; problemMessage=''; problemDetail='';
problemStack=repmat(struct('file','','name','','line',0),0,1);
failureTimeNs=NaN; failureReceiverState=''; completed=false; usage=struct();
try
    % Closure is logged immediately by native, while this MATLAB PHY
    % accounts for it at end-of-signal. Drain those callbacks after 330 s;
    % no new TX or external MAC state is admitted beyond the bound window.
    scheduler.run(drainUntilSec);
    sampler.verifyExhausted();
    usage=sampler.usage();
    completed=true;
catch problem
    problemId=problem.identifier;
    problemMessage=problem.message;
    problemDetail=getReport(problem,'extended','hyperlinks','off');
    problemStack=problem.stack;
    failureTimeNs=round(scheduler.Now*1e9);
    failureReceiverState=engine.state(4);
    usage=sampler.usage();
end
decisions=repmat(struct('tx_id',0,'source',0,'native_success',false, ...
    'matlab_success',false,'native_reason','','matlab_reason','missing', ...
    'native_rx_time_ns',0,'matlab_rx_time_ns',NaN,'same_success',false, ...
    'same_reason_group',false,'same_time',false,'same_collision',false, ...
    'same_errors',false,'all_matched',false),height(expected),1);
for i=1:height(expected)
    row=expected(i,:);
    found=find([observed.tx_id]==double(row.tx_id));
    result=decisions(i);
    result.tx_id=double(row.tx_id);
    result.source=double(row.source);
    result.native_success=logical(row.success);
    result.native_reason=char(row.reason);
    result.native_rx_time_ns=double(row.rx_time_ns);
    if numel(found)==1
        entry=observed(found);
        result.matlab_success=entry.success;
        result.matlab_reason=entry.reason;
        result.matlab_rx_time_ns=entry.time_ns;
        result.same_success=entry.success==logical(row.success);
        result.same_reason_group=reasonMatches(char(row.reason),entry.reason);
        if row.reason=="closure"
            % Native closure is emitted at TX start; the MATLAB signal
            % callback accounts for it at physical completion.
            result.same_time=double(row.rx_time_ns)==double(row.tx_time_ns) && ...
                abs(entry.time_ns-closureCompletionNs(double(row.tx_id)))<=2;
        else
            result.same_time=abs(entry.time_ns-double(row.rx_time_ns))<=2;
        end
        if isnan(double(row.collision_count))
            result.same_collision=true;
        else
            result.same_collision=entry.collision_count==double(row.collision_count);
        end
        result.same_errors=(isnan(double(row.header_errors)) || ...
            entry.header_errors==double(row.header_errors)) && ...
            (isnan(double(row.payload_errors)) || ...
            entry.payload_errors==double(row.payload_errors)) && ...
            (isnan(double(row.total_errors)) || ...
            entry.total_errors==double(row.total_errors));
    end
    result.all_matched=result.same_success && result.same_reason_group && ...
        result.same_time && result.same_collision && result.same_errors;
    decisions(i)=result;
end
intervalRows=repmat(struct('tx_id',0,'ordinal',0,'matched',false, ...
    'native_time_ns',0,'matlab_time_ns',NaN,'native_noise_watts',0, ...
    'matlab_noise_watts',NaN),height(intervals),1);
intervalOrderMatches=numel(observedIntervals)==height(intervals);
for i=1:height(intervals)
    row=intervals(i,:);
    compare=intervalRows(i);
    compare.tx_id=double(row.tx_id);
    compare.ordinal=double(row.interval_ordinal);
    compare.native_time_ns=double(row.time_ns);
    compare.native_noise_watts=double(row.noise_watts);
    if i<=numel(observedIntervals)
        seen=observedIntervals(i);
        compare.matlab_time_ns=seen.time_ns;
        compare.matlab_noise_watts=seen.noise_watts;
        sameJsr=(isinf(seen.jsr_db) && isinf(str2double(string(row.jsr_db))) && ...
                 sign(seen.jsr_db)==sign(str2double(string(row.jsr_db)))) || ...
            closeNumber(seen.jsr_db,str2double(string(row.jsr_db)),1e-6,1e-6);
        compare.matched=seen.tx_id==double(row.tx_id) && ...
            seen.ordinal==double(row.interval_ordinal) && ...
            abs(seen.time_ns-double(row.time_ns))<=2 && ...
            abs(seen.start_ns-double(row.interval_start_ns))<=2 && ...
            abs(seen.end_ns-double(row.interval_end_ns))<=2 && ...
            closeNumber(seen.noise_watts,double(row.noise_watts),1e-6,1e-25) && ...
            sameJsr && ...
            closeNumber(seen.offset_sec,double(row.offset_sec),1e-6,2e-9) && ...
            seen.collisions==double(row.collisions) && ...
            seen.same_rate==logical(row.same_rate_interference);
    end
    intervalRows(i)=compare;
end
intervalOrderMatches=intervalOrderMatches && all([intervalRows.matched]);
stateRows=repmat(struct('native_time_ns',0,'matlab_time_ns',NaN, ...
    'native_before','','native_after','','owner','', ...
    'matlab_before','','matlab_after','','observed',false,'matched',false), ...
    height(stateExpected),1);
for i=1:height(stateExpected)
    row=stateExpected(i,:);
    result=stateRows(i);
    result.native_time_ns=double(row.time_ns);
    result.native_before=char(row.state_before);
    result.native_after=char(row.state_after);
    result.owner=char(row.owner);
    if i<=numel(observedStates)
        seen=observedStates(i);
        result.matlab_time_ns=seen.time_ns;
        result.matlab_before=seen.state_before;
        result.matlab_after=seen.state_after;
        result.observed=true;
        result.matched=abs(seen.time_ns-double(row.time_ns))<=2 && ...
            strcmpi(seen.state_before,row.state_before) && ...
            strcmpi(seen.state_after,row.state_after);
    end
    stateRows(i)=result;
end
stateOrderMatches=numel(observedStates)==height(stateExpected) && all([stateRows.matched]);
ackRows=repmat(struct('tx_id',0,'source',0,'sequence',0,'frame_id',0, ...
    'native_success',false,'matlab_success',false,'matched',false),height(acks),1);
for i=1:height(acks)
    row=acks(i,:);
    target=find([decisions.tx_id]==double(row.tx_id));
    result=ackRows(i);
    result.tx_id=double(row.tx_id);
    result.source=double(row.source);
    result.sequence=double(row.sequence);
    result.frame_id=double(row.frame_id);
    result.native_success=logical(row.native_success);
    if numel(target)==1
        result.matlab_success=decisions(target).matlab_success;
        result.matched=decisions(target).same_success;
    end
    ackRows(i)=result;
end
passed=completed && numel(observed)==height(expected) && ...
    all([decisions.all_matched]) && intervalOrderMatches && stateOrderMatches && ...
    all([ackRows.matched]) && usage.unused==0;
status='mismatch_or_runtime_failure';
if passed, status='bounded_outcome_alignment'; end
report=struct('schema','csr-source5-node4-rx-replay-v1', ...
    'status',status,'completed',completed, ...
    'native_capture_bound',true,'bounded_outcome_alignment',passed, ...
    'same_input_outcome_alignment',passed, ...
    'node4_receiver_rule_parity',false, ...
    'rule_parity_limit',['Native prior_stage does not distinguish every ' ...
    'sync/acquisition/state rejection subtype.'], ...
    'full_network_parity',false,'scope',['Node-4 PHY decisions 300 <= t < 330 s, ' ...
    '299 recorded physical TXs, all 255 node-4 outcomes, native node-4 ' ...
    'MAC wake/sleep inputs; independent PHY state, ACK, draw and BER outputs.'], ...
    'native_decision_count',height(expected),'observed_decision_count',numel(observed), ...
    'matched_decisions',sum([decisions.all_matched]), ...
    'native_interval_count',height(intervals),'observed_interval_count',numel(observedIntervals), ...
    'matched_intervals',sum([intervalRows.matched]), ...
    'native_state_transition_count',height(stateExpected), ...
    'observed_state_transition_count',numel(observedStates), ...
    'matched_state_transitions',sum([stateRows.matched]), ...
    'state_order_alignment',stateOrderMatches, ...
    'state_history_exact',stateOrderMatches, ...
    'expected_state_count',height(stateExpected), ...
    'observed_state_count',numel(observedStates), ...
    'matched_state_count',sum([stateRows.matched]), ...
    'external_state_input_count',height(states), ...
    'audit_only_refresh_request_count',height(stateRequests), ...
    'ack_child_count',height(acks),'matched_ack_children',sum([ackRows.matched]), ...
    'ack_child_scope',['ACK child membership verified in native capture; ' ...
    'MATLAB ACK outcomes are inferred from the common physical aggregate ' ...
    'decision, not from a separate MATLAB child delivery callback.'], ...
    'source5_ack_child_count',sum(acks.source==5), ...
    'source5_ack_children_matched',sum([ackRows(acks.source==5).matched]), ...
    'draw_usage',usage,'error_identifier',problemId,'error_message',problemMessage, ...
    'error_detail',problemDetail,'error_stack',problemStack, ...
    'failure_time_ns',failureTimeNs,'error_time_seconds',failureTimeNs/1e9, ...
    'failure_receiver_state',failureReceiverState, ...
    'fixture_manifest_sha256',bound.fixture_manifest_sha256, ...
    'native_capture_manifest_sha256',bound.native_capture_manifest_sha256);
report.replay_drain_until_ns=round(drainUntilSec*1e9);
if ~isempty(outputDir)
    if ~isfolder(outputDir), mkdir(outputDir); end
    writetable(struct2table(decisions),fullfile(outputDir,'node4_decisions.csv'));
    writetable(struct2table(intervalRows),fullfile(outputDir,'node4_intervals.csv'));
    writetable(struct2table(ackRows),fullfile(outputDir,'node4_ack_children.csv'));
    writetable(struct2table(stateRows),fullfile(outputDir,'node4_states.csv'));
    writetable(struct2table(observedStates),fullfile(outputDir,'node4_observed_states.csv'));
    csr.validation.Artifacts.writeJson(fullfile(outputDir,'receiver_report.json'),report);
end

    function transmit(entry)
        frame=struct('Id',uint64(entry.tx_id),'SourceId',double(entry.node), ...
            'DestinationId',double(entry.peer), ...
            'WirePayloadBytes',double(entry.wire_bytes), ...
            'RateKeyKbps',double(entry.rate_kbps), ...
            'Preamble',char(entry.preamble),'TxPowerDbm',double(entry.tx_power_dbm));
        engine.transmit(frame,csr.phy.airtime(frame.WirePayloadBytes, ...
            frame.RateKeyKbps,frame.Preamble));
    end
    function externalState(entry)
        nativeChange=stateExpected(stateExpected.event_order==entry.event_order,:);
        if height(nativeChange)~=1 || nativeChange.owner~="external_mac" || ...
                ~strcmpi(engine.state(4),nativeChange.state_before)
            error('source5_receiver:ExternalStateOrder', ...
                'Native MAC wake/sleep at %.0f ns does not follow MATLAB state %s.', ...
                round(scheduler.Now*1e9),engine.state(4));
        end
        desired=char(entry.state);
        engine.setReceiverState(4,[upper(desired(1)) desired(2:end)]);
    end
    function stateChange(node,state)
        % Observe PHY-owned transitions; never feed the native result back
        % as a command before this model has independently produced it.
        if node~=4, return; end
        previous=lastNode4State;
        lastNode4State=char(state);
        at=round(scheduler.Now*1e9);
        if at<300e9 || at>=330e9, return; end
        observedStates(end+1,1)=struct('time_ns',at, ...
            'state_before',previous,'state_after',char(state));
    end
    function receive(frame,receiver,decision)
        if receiver~=4, return; end
        observed(end+1,1)=struct('tx_id',double(frame.Id), ...
            'receiver',double(receiver),'time_ns',round(scheduler.Now*1e9), ...
            'success',logical(decision.Success),'reason',char(decision.Reason), ...
            'collision_count',double(decision.CollisionCount), ...
            'header_errors',double(decision.HeaderErrors), ...
            'payload_errors',double(decision.PayloadErrors), ...
            'total_errors',double(decision.TotalErrors));
    end
    function traceInterval(name,frame,receiver,details)
        if receiver~=4 || ~strcmp(name,'phy_interval'), return; end
        key=double(frame.Id);
        count=1;
        if isKey(intervalOrdinals,key), count=intervalOrdinals(key)+1; end
        intervalOrdinals(key)=count;
        observedIntervals(end+1,1)=struct('tx_id',key,'ordinal',count, ...
            'time_ns',round(scheduler.Now*1e9), ...
            'start_ns',round(details.StartSec*1e9), ...
            'end_ns',round(details.EndSec*1e9), ...
            'noise_watts',double(details.NoisePowerWatts), ...
            'jsr_db',double(details.JsrDb), ...
            'offset_sec',double(details.TimeOffsetSeconds), ...
            'collisions',double(details.CollisionCount), ...
            'same_rate',logical(details.SameRateInterference));
    end
end

function tf=closeNumber(a,b,relative,absolute)
tf=isfinite(a) && isfinite(b) && abs(a-b)<=max(absolute,relative*max(abs(a),abs(b)));
end

function tf=reasonMatches(native,candidate)
if strcmp(native,'prior_stage')
    tf=any(strcmp(candidate,{'prior_stage','receiver_state','not_acquired', ...
        'acquisition_rejected','sync_threshold','half_duplex'}));
else
    tf=strcmp(native,candidate);
end
end
