function summary=run_two_replays(candidateRoot,kitRoot,nativeRoot,outputRoot,phyDrawCsv,boundNode4Dir)
%RUN_TWO_REPLAYS Run both short-case MATLAB checks after the native captures.
% The discovery check is observational even with bound PHY draws. Source-5
% HOP and MAC checks are separate conditional boundaries, never a claim of
% complete NWK/receiver or six-thousand-second network parity.
if nargin<5, phyDrawCsv=''; end
if nargin<6 || isempty(boundNode4Dir)
    boundNode4Dir=fullfile(nativeRoot,'bound_node4');
end
batchPath=fullfile(nativeRoot,'batch.json');
if ~isfile(batchPath)
    error('two_case:NativeBatch','First run both native captures.');
end
batch=jsondecode(fileread(batchPath));
if ~strcmp(batch.schema,'csr-two-case-native-batch-v1') || ...
        ~batch.both_captures_verified || ~batch.discovery131.verified || ...
        ~batch.source5_132.verified
    error('two_case:CaptureFidelity','A native capture failed exact original-prefix fidelity.');
end
if ~isfile(phyDrawCsv)
    error('two_case:PhyDraws','Convert the verified discovery capture into a PHY draw CSV first.');
end
addpath(candidateRoot);
addpath(fullfile(kitRoot,'discovery_replay'));
addpath(fullfile(kitRoot,'source5_replay'));
addpath(fullfile(kitRoot,'source5_receiver_replay'));
if ~isfolder(outputRoot), mkdir(outputRoot); end
summary=struct('schema','csr-two-case-matlab-summary-v1', ...
    'native_prefixes_verified',true, ...
    'discovery',struct('completed',false,'bounded_rule_parity',false), ...
    'node4_receiver',struct('completed',false,'bounded_outcome_alignment',false, ...
                            'node4_receiver_rule_parity',false), ...
    'source5_capacity',struct('completed',false,'pass',false), ...
    'source5_mac',struct('completed',false,'pass',false), ...
    'full_network_parity_claim',false);
try
    result=run_discovery_replay(candidateRoot, ...
        fullfile(kitRoot,'discovery_replay','fixture'), ...
        fullfile(outputRoot,'discovery'),phyDrawCsv);
    summary.discovery=struct('completed',result.completed, ...
        'matched_success_flags',result.matched_success_flags, ...
        'exact_outcomes',result.exact_outcomes, ...
        'skipped_external_state_inputs',result.skipped_external_state_inputs, ...
        'decision_count',result.decision_count, ...
        'bounded_rule_parity',result.native_parity_gate_pass, ...
        'gate_reason',result.native_parity_gate_reason);
    for name={'primary_result','control_result'}
        if isfield(result,name{1}), summary.discovery.(name{1})=result.(name{1}); end
    end
catch problem
    summary.discovery=struct('completed',false,'bounded_rule_parity',false, ...
        'error_identifier',problem.identifier,'error_message',problem.message);
end
try
    result=run_source5_receiver_replay(candidateRoot,boundNode4Dir, ...
        fullfile(outputRoot,'node4_receiver'));
    summary.node4_receiver=struct('completed',result.completed, ...
        'bounded_outcome_alignment',result.bounded_outcome_alignment, ...
        'node4_receiver_rule_parity',result.node4_receiver_rule_parity, ...
        'matched_decisions',result.matched_decisions, ...
        'native_decision_count',result.native_decision_count, ...
        'matched_ack_children',result.matched_ack_children, ...
        'ack_child_count',result.ack_child_count);
    for name={'error_identifier','error_message','error_time_seconds', ...
            'state_history_exact','expected_state_count','observed_state_count','matched_state_count'}
        if isfield(result,name{1}), summary.node4_receiver.(name{1})=result.(name{1}); end
    end
catch problem
    summary.node4_receiver=struct('completed',false, ...
        'bounded_outcome_alignment',false,'node4_receiver_rule_parity',false, ...
        'error_identifier',problem.identifier,'error_message',problem.message);
end
try
    result=run_source5_capacity_replay( ...
        fullfile(kitRoot,'source5_replay','fixtures'), ...
        fullfile(outputRoot,'source5_capacity'),'actual-tx');
    summary.source5_capacity=struct('completed',result.completed, ...
        'pass',result.pass,'comparison',result.comparison);
catch problem
    summary.source5_capacity=struct('completed',false,'pass',false, ...
        'error_identifier',problem.identifier,'error_message',problem.message);
end
try
    result=run_source5_mac_replay( ...
        fullfile(kitRoot,'source5_replay','mac_adapter'), ...
        fullfile(nativeRoot,'seed132'),fullfile(outputRoot,'source5_mac'), ...
        candidateRoot);
    summary.source5_mac=struct('completed',result.completed,'pass',result.pass, ...
        'status',result.status,'error_identifier',result.error_identifier, ...
        'error_message',result.error_message);
catch problem
    summary.source5_mac=struct('completed',false,'pass',false, ...
        'error_identifier',problem.identifier,'error_message',problem.message);
end
fid=fopen(fullfile(outputRoot,'summary.json'),'w');
if fid<0, error('two_case:Output','Cannot write replay summary.'); end
cleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(summary,'PrettyPrint',true));
end
