function report=run_discovery_replay(runtimeRoot,fixtureRoot,outputDir,phyDrawCsv)
%RUN_DISCOVERY_REPLAY Replay native startup TX/wake history through CSR PHY.
% Observational without PHY draw tape; completed common-input PHY checks only
% when the separately bound capture supplies every receiver draw and child.
% First argument is the candidate tree containing +csr, not runtime/fix.
if nargin<2 || isempty(fixtureRoot)
    fixtureRoot=fullfile(fileparts(mfilename('fullpath')),'fixture');
end
if nargin<3, outputDir=''; end
if nargin<4, phyDrawCsv=''; end
if ~isfolder(runtimeRoot) || ~isfolder(fullfile(runtimeRoot,'+csr'))
    error('discovery_replay:Runtime','Supply candidate tree containing +csr.');
end
addpath(runtimeRoot);
if ~isempty(phyDrawCsv)
    if ~isfile(phyDrawCsv)
        error('discovery_replay:Tape','PHY draw tape does not exist.');
    end
    if ~strcmp(csr.validation.Artifacts.sha256(fullfile(runtimeRoot,'+csr','+phy','SignalEngine.m')), ...
            '289c764bac0de95fefa75812e1b5090dcdf1953e35960cf7f02c4e298f4e294e')
        error('discovery_replay:SeamBinding','Production SignalEngine changed; re-audit test copy.');
    end
end
manifest=jsondecode(fileread(fullfile(fixtureRoot,'manifest.json')));
if ~strcmp(manifest.schema,'csr-discovery-observed-history-v1') || ...
        ~isequal(double(manifest.window_ns(:))',[25e9 85e9])
    error('discovery_replay:Manifest','Unknown or altered native-history fixture.');
end
rows=repmat(struct('seed',0,'tx_id',0,'receiver',0,'source',0, ...
    'native_success',false,'matlab_success',false,'same_success',false, ...
    'native_reason','','matlab_reason','','native_time_ns',0,'matlab_time_ns',0, ...
    'native_collision_count',0,'matlab_collision_count',0, ...
    'native_total_errors',0,'matlab_total_errors',0),0,1);
cases=repmat(struct('seed',0,'completed',false,'target_count',0, ...
    'matched_decision_count',0,'native_successes',0,'matlab_successes',0, ...
    'skipped_external_state_count',0,'transmission_count',0, ...
    'error_identifier','','error_message','','error_stack',struct([]), ...
    'error_time_seconds',NaN,'draw_usage',struct(), ...
    'capture_bindings_verified',false,'exogenous_state_input_count',0, ...
    'audit_state_count',0,'observed_state_count',0,'matched_state_count',0, ...
    'state_history_exact',false),0,1);
actionTrace=repmat(struct('seed',0,'trace_order',0,'time_seconds',0, ...
    'time_ns',0,'kind','','node',0,'tx_id',0,'recorded_order',0, ...
    'state_before','','state_after','','success',false,'reason',''),0,1);
for seed=[131 132]
    [caseRows,result]=oneCase(seed);
    rows=[rows;caseRows]; %#ok<AGROW>
    cases(end+1,1)=result; %#ok<AGROW>
end
commonDraws=~isempty(phyDrawCsv);
report=struct('schema','csr-discovery-history-replay-v1', ...
    'runtime',version,'completed',all([cases.completed]), ...
    'status','observational_reconstruction', ...
    'matched_success_flags',sum([rows.same_success]), ...
    'matched_arrival_times',sum([rows.native_time_ns]==[rows.matlab_time_ns]), ...
    'matched_collision_counts',sum([rows.native_collision_count]==[rows.matlab_collision_count]), ...
    'matched_error_counts',sum([rows.native_total_errors]==[rows.matlab_total_errors]), ...
    'exact_outcomes',sum([rows.same_success] & ...
        [rows.native_time_ns]==[rows.matlab_time_ns] & ...
        [rows.native_collision_count]==[rows.matlab_collision_count] & ...
        [rows.native_total_errors]==[rows.matlab_total_errors]), ...
    'skipped_external_state_inputs',sum([cases.skipped_external_state_count]), ...
    'decision_count',numel(rows), ...
    'capture_common_inputs_complete',false, ...
    'native_parity_gate_pass',false, ...
    'native_parity_gate_reason','native aggregate children/PHY draws and prefix fidelity are not bound', ...
    'phy_draw_tape_supplied',commonDraws, ...
    'scope',['Primary: seed 131 captured draws and actual MAC wake/sleep inputs, ' ...
        '25 <= t < 85 s, receivers 2 and 5. PHY owns Track/Tx completion. ' ...
        'Seed 132 is a separate archived positive control without native PHY draw tape. ' ...
        'No network, MAC scheduling or NWK handoff parity claim.'], ...
    'cases',cases,'rows',rows);
if commonDraws
    report.status='captured_phy_draw_reconstruction';
    report.native_parity_gate_reason=['Receiver reconstruction only; seed 132 controls lack captured draws; ' ...
        'full network scheduling, aggregate-child delivery and NWK/HOP effects are outside this test.'];
end
report.primary_result=summarizeCase(131);
report.control_result=summarizeCase(132);
if ~isempty(outputDir)
    if ~isfolder(outputDir), mkdir(outputDir); end
    writetable(struct2table(actionTrace),fullfile(outputDir,'action_trace.csv'));
    writetable(struct2table(rows),fullfile(outputDir,'decisions.csv'));
    csr.validation.Artifacts.writeJson(fullfile(outputDir,'report.json'),report);
end

    function [outRows,result]=oneCase(seed)
        folder=fullfile(fixtureRoot,sprintf('s%d',seed));
        name={'tx.csv','states.csv','initial_states.csv','expected.csv','scenario.csv'};
        info=manifest.cases([manifest.cases.seed]==seed);
        for j=1:numel(name)
            actual=csr.validation.Artifacts.sha256(fullfile(folder,name{j}));
            expectedHash=info.fixture_sha256.(strrep(name{j},'.','_'));
            if ~strcmp(actual,expectedHash)
                error('discovery_replay:FixtureHash','Changed native fixture %s.',name{j});
            end
        end
        tx=readtable(fullfile(folder,'tx.csv'),'TextType','string');
        states=readtable(fullfile(folder,'states.csv'),'TextType','string');
        initial=readtable(fullfile(folder,'initial_states.csv'),'TextType','string');
        [states,stateAudit]=classifyActualStates(states,initial);
        % TX history is imposed for every node. Receiver duty inputs and
        % output-state assertions belong only to the checked receivers.
        if seed==131, checkedReceivers=[2 5]; else, checkedReceivers=2; end
        states=states(ismember(states.node,checkedReceivers),:);
        stateAudit=stateAudit(ismember(stateAudit.node,checkedReceivers),:);
        captureBindingsVerified=false;
        if seed==131 && ~isempty(phyDrawCsv)
            captureDir=fileparts(phyDrawCsv);
            provenanceFile=fullfile(captureDir,'phy_draws.provenance.json');
            actualTx=fullfile(captureDir,'tx_inputs.csv');
            stateAuditFile=fullfile(captureDir,'receiver_state_audit.csv');
            requestAuditFile=fullfile(captureDir,'receiver_request_audit.csv');
            nativeTraceFile=fullfile(captureDir,'ns3-trace.csv');
            external=fullfile(fileparts(phyDrawCsv),'receiver_inputs.csv');
            if ~isfile(external) || ~isfile(actualTx) || ~isfile(provenanceFile)
                error('discovery_replay:ExternalState', ...
                    'Bound native TX power, PHY draws and receiver states are required.');
            end
            provenance=jsondecode(fileread(provenanceFile));
            if ~strcmp(provenance.schema,'csr-discovery-bound-phy-draws-v2') || ...
                    ~strcmp(provenance.state_input_policy,'actual_idle_search_transitions_only') || ...
                    ~strcmp(provenance.fixture_states_sha256,info.fixture_sha256.states_csv) || ...
                    ~strcmp(provenance.fixture_initial_states_sha256,info.fixture_sha256.initial_states_csv) || ...
                    ~strcmp(provenance.native_state_trace_sha256,csr.validation.Artifacts.sha256(nativeTraceFile)) || ...
                    ~strcmp(provenance.receiver_state_audit_sha256,csr.validation.Artifacts.sha256(stateAuditFile)) || ...
                    ~strcmp(provenance.receiver_request_audit_sha256,csr.validation.Artifacts.sha256(requestAuditFile)) || ...
                    ~strcmp(provenance.fixture_tx_sha256,info.fixture_sha256.tx_csv) || ...
                    ~strcmp(provenance.capture_sha256, ...
                        csr.validation.Artifacts.sha256(fullfile(captureDir,'capture.jsonl'))) || ...
                    ~strcmp(provenance.draws_sha256,csr.validation.Artifacts.sha256(phyDrawCsv)) || ...
                    ~strcmp(provenance.tx_inputs_sha256,csr.validation.Artifacts.sha256(actualTx)) || ...
                    ~strcmp(provenance.receiver_inputs_sha256,csr.validation.Artifacts.sha256(external))
                error('discovery_replay:CaptureBinding','Native capture hash binding failed.');
            end
            originalTx=tx;
            tx=readtable(actualTx,'TextType','string');
            states=readtable(external,'TextType','string');
            stateAudit=readtable(stateAuditFile,'TextType','string');
            captureBindingsVerified=true;
            if height(tx)~=info.tx_count || ...
                    ~isequal(tx.Properties.VariableNames,originalTx.Properties.VariableNames)
                error('discovery_replay:ActualTx','Captured TX input schema/count differs.');
            end
            shared=setdiff(tx.Properties.VariableNames,{'tx_power_dbm'});
            for j=1:numel(shared)
                field=shared{j};
                if ~isequal(tx.(field),originalTx.(field))
                    error('discovery_replay:ActualTx', ...
                        'Captured TX changes accepted history field %s.',field);
                end
            end
            if any(~ismember(states.node,[2 5])) || ...
                    any(~ismember(states.state,["idle","search"])) || ...
                    any(~ismember(states.origin,["external_wake","external_sleep"])) || ...
                    any(states.state_before==states.state)
                error('discovery_replay:ExternalState','Invalid external receiver states.');
            end
        end
        initial=readtable(fullfile(folder,'initial_states.csv'),'TextType','string');
        expected=readtable(fullfile(folder,'expected.csv'),'TextType','string');
        assert(height(expected)==info.target_count && height(tx)==info.tx_count);
        scheduler=csr.sim.EventScheduler(500000);
        streams=csr.sim.RandomStreams(seed);
        config=csr.scenario.importNs3(fullfile(folder,'scenario.csv'), ...
            struct('HistoricalBenchmark',true));
        config.DurationSeconds=85;
        observed=repmat(struct('tx_id',0,'receiver',0,'source',0, ...
            'time_ns',0,'success',false,'reason','','collision_count',0, ...
            'total_errors',0),0,1);
        stateSkips=0; sampler=[];
        observedStates=repmat(struct('time_ns',0,'node',0,'state',""),0,1);
        % The bounded new capture covers seed 131. Seed 132 remains a
        % separately measured, positive long-preamble physical control.
        if seed==131 && ~isempty(phyDrawCsv)
            sampler=DiscoveryReplaySampler(phyDrawCsv,[2 5],@()scheduler.Now);
            engine=DiscoverySignalEngine(config,scheduler,streams,@receive,[],@stateChange,[],sampler);
        else
            engine=csr.phy.SignalEngine(config,scheduler,streams,@receive,[],@stateChange);
        end
        for i=1:height(initial)
            if strcmp(initial.state(i),'idle')
                engine.setReceiverState(initial.node(i),'Idle');
            end
        end
        actions=[table(double(tx.time_ns),double(tx.event_order), ...
                    repmat("tx",height(tx),1),(1:height(tx))', ...
                    'VariableNames',{'time_ns','event_order','kind','index'}); ...
                 table(double(states.time_ns),double(states.event_order), ...
                    repmat("state",height(states),1),(1:height(states))', ...
                    'VariableNames',{'time_ns','event_order','kind','index'})];
        actions=sortrows(actions,{'time_ns','event_order'});
        for i=1:height(actions)
            if actions.time_ns(i)<25e9 || actions.time_ns(i)>=85e9
                error('discovery_replay:Window','Event outside replay window.');
            end
            at=actions.time_ns(i)/1e9;
            if actions.kind(i)=="tx"
                row=tx(actions.index(i),:);
                scheduler.scheduleAt(at,@()transmit(row));
            else
                row=states(actions.index(i),:);
                scheduler.scheduleAt(at,@()externalState(row));
            end
        end
        result=struct('seed',seed,'completed',false,'target_count',height(expected), ...
            'matched_decision_count',0,'native_successes',sum(expected.success), ...
            'matlab_successes',0,'skipped_external_state_count',0, ...
            'transmission_count',height(tx),'error_identifier','','error_message','', ...
            'error_stack',struct([]),'error_time_seconds',NaN,'draw_usage',struct(), ...
            'capture_bindings_verified',captureBindingsVerified, ...
            'exogenous_state_input_count',height(states),'audit_state_count',height(stateAudit), ...
            'observed_state_count',0,'matched_state_count',0,'state_history_exact',false);
        try
            scheduler.run(85);
            if ~isempty(sampler), sampler.verifyExhausted(); result.draw_usage=sampler.usage(); end
            result.completed=true;
        catch problem
            result.error_identifier=problem.identifier;
            result.error_message=problem.message;
            result.error_stack=problem.stack;
            result.error_time_seconds=scheduler.Now;
            traceAction('error',0,0,0,'','',false,problem.message);
        end
        result.skipped_external_state_count=stateSkips;
        auditNodes=unique(stateAudit.node);
        seen=struct2table(observedStates);
        seen=seen(ismember(seen.node,auditNodes),:);
        result.observed_state_count=height(seen);
        for auditNode=auditNodes'
            nativeState=stateAudit(stateAudit.node==auditNode,:);
            replayState=seen(seen.node==auditNode,:);
            count=min(height(nativeState),height(replayState));
            result.matched_state_count=result.matched_state_count + ...
                sum(nativeState.time_ns(1:count)==replayState.time_ns(1:count) & ...
                    nativeState.state(1:count)==replayState.state(1:count));
        end
        result.state_history_exact=result.matched_state_count==height(stateAudit) && ...
            height(seen)==height(stateAudit);
        if ~isempty(outputDir)
            if ~isfolder(outputDir), mkdir(outputDir); end
            writetable(seen,fullfile(outputDir,sprintf('s%d_observed_states.csv',seed)));
            writetable(stateAudit,fullfile(outputDir,sprintf('s%d_expected_states.csv',seed)));
        end
        outRows=repmat(rows,0,1);
        for i=1:height(expected)
            native=expected(i,:);
            found=find([observed.tx_id]==native.tx_id & ...
                [observed.receiver]==native.receiver);
            row=struct('seed',seed,'tx_id',double(native.tx_id), ...
                'receiver',double(native.receiver),'source',double(native.source), ...
                'native_success',logical(native.success),'matlab_success',false, ...
                'same_success',false,'native_reason',char(native.reason), ...
                'matlab_reason','missing','native_time_ns',double(native.receive_time_ns), ...
                'matlab_time_ns',NaN,'native_collision_count',double(native.collision_count), ...
                'matlab_collision_count',NaN, ...
                'native_total_errors',double(native.total_errors), ...
                'matlab_total_errors',NaN);
            if numel(found)==1
                seen=observed(found);
                row.matlab_success=seen.success;
                row.same_success=seen.success==logical(native.success);
                row.matlab_reason=seen.reason;
                row.matlab_time_ns=seen.time_ns;
                row.matlab_collision_count=seen.collision_count;
                row.matlab_total_errors=seen.total_errors;
            end
            outRows(end+1,1)=row; %#ok<AGROW>
        end
        result.matched_decision_count=sum([outRows.same_success]);
        result.matlab_successes=sum([outRows.matlab_success]);

        function transmit(entry)
            traceAction('tx_input',entry.node,entry.tx_id,entry.event_order, ...
                engine.state(entry.node),'Tx',false,'native_transmission');
            frame=struct('Id',uint64(entry.tx_id),'SourceId',double(entry.node), ...
                'DestinationId',double(entry.peer),'WirePayloadBytes',double(entry.wire_bytes), ...
                'RateKeyKbps',double(entry.rate_kbps), ...
                'Preamble',char(entry.preamble),'TxPowerDbm',double(entry.tx_power_dbm));
            duration=csr.phy.airtime(frame.WirePayloadBytes,frame.RateKeyKbps,frame.Preamble);
            engine.transmit(frame,duration);
        end
        function externalState(entry)
            before=engine.state(entry.node);
            desired=char(entry.state);
            traceAction('external_state_input',entry.node,0,entry.event_order, ...
                before,desired,false,char(entry.origin));
            if ~strcmpi(before,char(entry.state_before))
                error('discovery_replay:ExternalStateConflict', ...
                    ['At %.9f s node %d external %s expected %s, but receiver is %s. ' ...
                    'See action_trace.csv; no state was forced.'], ...
                    scheduler.Now,entry.node,char(entry.origin),char(entry.state_before),before);
            end
            engine.setReceiverState(entry.node, [upper(desired(1)) desired(2:end)]);
        end
        function stateChange(node,value)
            % PHY owns Track/Tx and their returns to Search. These callbacks
            % are observations, never reinserted as external state inputs.
            if scheduler.Now<25, return; end
            observedStates(end+1,1)=struct('time_ns',round(scheduler.Now*1e9), ...
                'node',double(node),'state',string(lower(value)));
            traceAction('observed_state',node,0,0,'',value,false,'phy_or_external_transition');
        end
        function receive(frame,receiver,decision)
            entry=struct('tx_id',double(frame.Id),'receiver',double(receiver), ...
                'source',double(frame.SourceId),'time_ns',round(scheduler.Now*1e9), ...
                'success',logical(decision.Success),'reason',char(decision.Reason), ...
                'collision_count',double(decision.CollisionCount), ...
                'total_errors',double(decision.TotalErrors));
            observed(end+1,1)=entry;
            traceAction('receive_decision',receiver,frame.Id,0,engine.state(receiver), ...
                engine.state(receiver),decision.Success,decision.Reason);
        end
        function traceAction(kind,node,txId,recordedOrder,before,after,success,reason)
            actionTrace(end+1,1)=struct('seed',seed,'trace_order',numel(actionTrace)+1, ...
                'time_seconds',scheduler.Now,'time_ns',round(scheduler.Now*1e9), ...
                'kind',char(kind),'node',double(node),'tx_id',double(txId), ...
                'recorded_order',double(recordedOrder),'state_before',char(before), ...
                'state_after',char(after),'success',logical(success),'reason',char(reason));
        end
    end
    function summary=summarizeCase(seed)
        selected=rows([rows.seed]==seed);
        result=cases([cases.seed]==seed);
        exact=[selected.same_success] & ...
            [selected.native_time_ns]==[selected.matlab_time_ns] & ...
            [selected.native_collision_count]==[selected.matlab_collision_count] & ...
            [selected.native_total_errors]==[selected.matlab_total_errors];
        if seed==131
            scope='Primary captured seed 131 PHY reconstruction, receivers 2 and 5';
        else
            scope='Archived seed 132 receiver-2 positive controls; native PHY draws unavailable, observational only';
        end
        summary=struct('seed',seed,'scope',scope,'completed',result.completed, ...
            'target_count',numel(selected),'exact_outcomes',sum(exact), ...
            'target_outcomes_exact',result.completed && all(exact), ...
            'matched_success_flags',sum([selected.same_success]), ...
            'matched_arrival_times',sum([selected.native_time_ns]==[selected.matlab_time_ns]), ...
            'matched_collision_counts',sum([selected.native_collision_count]==[selected.matlab_collision_count]), ...
            'matched_error_counts',sum([selected.native_total_errors]==[selected.matlab_total_errors]), ...
            'capture_bindings_verified',result.capture_bindings_verified, ...
            'state_history_exact',result.state_history_exact, ...
            'expected_state_count',result.audit_state_count, ...
            'observed_state_count',result.observed_state_count, ...
            'matched_state_count',result.matched_state_count);
    end
end

function [inputs,audit]=classifyActualStates(states,initial)
% Classify actual archived state transitions; requests/refreshes are not inputs.
previous=containers.Map('KeyType','double','ValueType','char');
for i=1:height(initial), previous(initial.node(i))=char(initial.state(i)); end
audit=states;
audit.state_before=strings(height(states),1);
audit.origin=strings(height(states),1);
for i=1:height(states)
    node=states.node(i); before=previous(node); after=char(states.state(i));
    previous(node)=after; audit.state_before(i)=string(before);
    pair=[before '>' after];
    switch pair
        case 'idle>search', origin="external_wake";
        case 'search>idle', origin="external_sleep";
        case 'search>track', origin="phy_acquisition";
        case 'track>search', origin="phy_receive_completion";
        case {'idle>tx','search>tx','track>tx'}, origin="phy_transmit_start";
        case 'tx>search', origin="phy_transmit_completion";
        otherwise
            error('discovery_replay:StateOwnership','Unclassified native state transition %s.',pair);
    end
    audit.origin(i)=origin;
end
audit=audit(:,{'time_ns','event_order','node','state_before','state','origin'});
inputs=audit(startsWith(audit.origin,"external_"),:);
end
