function [cases,plan,retained,sweeps,campus,retainedPlan,sweepPlan] = tranche10Suite()
%TRANCHE10SUITE Fixed timing contracts, regression workloads and campus6000.
% Construction does not execute simulations or establish parity. The complete
% accepted stimuli are reused, including the campus admission-trace budget.
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
plan=jsondecode(fileread(fullfile(root,'scenarios','contention_timing','plan.json')));
keys={'c129','c128','c130','c131','c132','a129'};
if ~strcmp(plan.schema,'csr-contention-timing-plan-v1') || ...
        ~strcmp(plan.matlab_base_commit,'386f669f369f90b18d1d553db85b017b0ca8c77c') || ...
        ~strcmp(plan.accepted_tranche9_matlab_commit,'99fff0381fe9621ccd76fbdce41eac9aba5a9469') || ...
        ~strcmp(plan.ns3_source_commit,'486d9e01f010fdfd4c6aebb87c6d7e51fc674a5b') || ...
        plan.diagnostic_case_count~=6 || ~isequal(plan.diagnostic_order(:)',keys) || ...
        ~isequal(plan.control_keys(:)',{'c129','a129'}) || ...
        ~isequal(plan.service_window_s(:)',[300 320]) || ...
        ~plan.service_window_end_exclusive || plan.service_max_records~=100000 || ...
        plan.feedback_max_records~=100000 || plan.retained_case_count~=29 || ...
        plan.sweep_case_count~=18 || plan.stimuli_changed || ...
        ~plan.policy_changes || plan.phy_ecc_changed || plan.radio_policy_changed || plan.rng_policy_changed
    error('csr:timing:Plan','Unexpected candidate, source, case membership or scope.');
end
if ~strcmp(plan.diagnostic_plan,'scenarios/ack_service/plan.json') || ...
        ~strcmp(plan.diagnostic_plan_sha256,'372db92a385781d9854a096149fd419b90ae79823125b79269506bd9877e0116')
    error('csr:timing:Plan','The accepted Tranche 9 diagnostic plan is required.');
end
contractReferences=struct('kind',{'mac','rx','ack'}, ...
    'directory',{'evidence/tranche-10-contract-reference','evidence/tranche-10-receiver-reference', ...
        'evidence/tranche-9-contract-reference'}, ...
    'reference_schema',{'csr-tranche10-contention-contract-reference-v1', ...
        'csr-tranche10-receiver-contract-reference-v1','csr-tranche9-ack-contract-reference-v1'}, ...
    'summary_schema',{'csr-tranche10-contention-contract-v1', ...
        'csr-tranche10-receiver-contract-v1','csr-tranche9-ack-service-contract-v1'});
referenceDirectories={'evidence/tranche-7-ns3-reference','evidence/tranche-7-benchmark-inputs', ...
    'evidence/tranche-8-ns3-reference','evidence/tranche-9-ns3-reference', ...
    'evidence/tranche-9-contract-reference','evidence/tranche-10-contract-reference', ...
    'evidence/tranche-10-receiver-reference','evidence/tranche-10-native-build'};
if ~isequal(orderfields(plan.contract_references(:)),orderfields(contractReferences(:))) || ...
        ~isequal(plan.reference_directories(:)',referenceDirectories) || ...
        ~isequal({plan.reference_files.path}, ...
            {'evidence/tranche-10-native-build.json','evidence/tranche-10-source-recheck.json'})
    error('csr:timing:Plan','Contract families, order or reference directories changed.');
end
checkFile(root,struct('path',plan.diagnostic_plan,'sha256',plan.diagnostic_plan_sha256));
for k=1:numel(plan.input_files), checkFile(root,plan.input_files(k)); end
for k=1:numel(plan.reference_files), checkFile(root,plan.reference_files(k)); end
if ~isequal([plan.accepted_anchors.tranche],[7 8 9])
    error('csr:timing:Anchor','Expected accepted Tranche 7, 8 and 9 evidence archives.');
end
archiveHashes={'ea39b86ef68f91a551e4e22d176e2e96dc5305f33673741eee0adc6039599655', ...
    'bfc4f7f05f0800316b371df3ec316f309f14e3482ef259c3f9c7bd7eea025d77', ...
    'ddcede0a83b5ff906a7736f63406fc4cecb11e841795e39e93237364e0e11edf'};
for k=1:3
    anchor=plan.accepted_anchors(k); number=anchor.tranche;
    if ~strcmp(anchor.path,sprintf('evidence/tranche-%d-r2025a-accepted/tranche%d_evidence.zip',number,number)) || ...
            ~strcmp(anchor.sha256,archiveHashes{k})
        error('csr:timing:Anchor','Accepted archive identity changed.');
    end
    checkFile(root,anchor);
end
[cases,diagnosticPlan]=csr.scenario.ackServiceSuite();
if ~isequal({cases.StorageKey},keys) || ...
        ~isequal(diagnosticPlan.control_keys(:)',plan.control_keys(:)')
    error('csr:timing:Plan','Accepted diagnostics or controls changed.');
end
[retained,retainedPlan]=csr.scenario.retainedSuite();
[sweeps,sweepPlan]=csr.scenario.researchSweep();
if numel(sweeps)~=18 || numel(plan.sweep_cases)~=18
    error('csr:timing:SweepPlan','Expected the unchanged 18-case default sweep.');
end
for k=1:numel(sweeps)
    key=sprintf('%02d',k);
    if ~strcmp(sweeps(k).CaseId,plan.sweep_cases(k).case_id) || ...
            ~strcmp(key,plan.sweep_cases(k).storage_key)
        error('csr:timing:SweepPlan','Sweep identity, order or storage mapping changed.');
    end
    sweeps(k).StorageKey=key;
end
campus=csr.scenario.benchmarkSuite(struct('Cases',{{'campus_multihop_6000'}}));
catalog=jsondecode(fileread(fullfile(root,'scenarios','benchmarks','catalog.json')));
entries=catalog.cases; if isstruct(entries), entries=num2cell(entries); end
index=find(cellfun(@(x)strcmp(x.case_id,'campus_multihop_6000'),entries));
if numel(index)~=1 || ~strcmp(plan.campus.storage_key,'campus') || ...
        ~isequal(orderfields(rmfield(plan.campus,'storage_key')),orderfields(entries{index})) || ...
        numel(campus)~=1 || campus.DurationSeconds~=6000 || campus.Seed~=128
    error('csr:timing:CampusPlan','Campus identity, catalog or duration changed.');
end
campus.StorageKey='campus';
end

function checkFile(root,entry)
path=csr.validation.Artifacts.canonicalPath(fullfile(root,entry.path));
root=csr.validation.Artifacts.canonicalPath(root);
if ~startsWith(path,[root filesep]) || ~isfile(path) || ...
        ~strcmp(csr.validation.Artifacts.sha256(path),entry.sha256)
    error('csr:timing:InputChanged','A retained factory, catalog or input artifact changed.');
end
if isfield(entry,'bytes')
    info=dir(path);
    if info.bytes~=entry.bytes, error('csr:timing:InputChanged','Input size changed.'); end
end
end
