function report=noPathWirePreflight(config,folder)
%NOPATHWIREPREFLIGHT Public forwarded-DATA rejection preserves NoPath semantics.
if ~isfolder(folder), mkdir(folder); end
checks=struct('name',{},'passed',{},'details',{}); profile=config.Nwk.SecurityProfile;
payload=struct('Subtype','no_path','TargetId',8,'Sequence',uint32(0),'Generation',0);
assert(csr.nwk.controlWireBytes('NEIGHBOR_CHECK',payload,1,profile)==19 && ...
    ac.controlWireBytes('NEIGHBOR_CHECK',payload,1,profile)==16, ...
    'autocase:NoPathWirePreflight','NoPath compatibility metadata size was not corrected.');
checks(end+1)=checked('no_path_metadata_is_not_charged_as_raw_body', ...
    struct('baseline_bytes',19,'candidate_bytes',16,'target_id',payload.TargetId));

% Use the real public DATA rejection branch to create the reliable control.
% Forwarding disable is an ordinary fixture configuration, not a private
% state override or an alteration of the owner network scenario.
[layer,clock,probe]=ac.ControlWireProbe.fixture(config,false); probe.activatePeer(3);
app=struct('Id',uint64(9201),'SourceId',3,'DestinationId',8,'GeneratedSeconds',0, ...
    'ApplicationPayloadBytes',0,'HopCount',0,'Traversal',3);
[accepted,reason]=layer.receiveData(app,3); clock.run(0); row=probe.last('NEIGHBOR_CHECK','no_path');
assert(~accepted && strcmp(reason,'transit_disabled') && isequal(row.peers,3) && ...
    row.options.AckRequired && row.frame.AckRequired && row.control.WirePayloadBytes==16 && ...
    row.frame.WirePayloadBytes==16 && isequal(row.control.Payload,payload) && ...
    isequal(row.frame.Control.Payload,payload), ...
    'autocase:NoPathWirePreflight','Public NoPath callback/frame changed its target, reliability or metadata.');
checks(end+1)=checked('public_data_rejection_emits_reliable_compact_no_path', ...
    struct('reason',reason,'destination',row.peers,'target_id',row.control.Payload.TargetId, ...
    'wire_bytes',row.frame.WirePayloadBytes,'ack_required',row.frame.AckRequired));

% Other NeighborCheck subtypes and sibling controls retain baseline sizes.
for subtype={'discovery','message','overheard','verify'}
    sibling=struct('Subtype',subtype{1},'Sequence',0,'Active',false,'Generation',0);
    assert(ac.controlWireBytes('NEIGHBOR_CHECK',sibling,1,profile)== ...
        csr.nwk.controlWireBytes('NEIGHBOR_CHECK',sibling,1,profile), ...
        'autocase:NoPathWirePreflight','Another NeighborCheck subtype changed size.');
end
for kind={'DISCOVER','KEY_REQUEST','KEY_UPDATE','SNMP_START','SNMP_DONE'}
    sibling=struct();
    assert(ac.controlWireBytes(kind{1},sibling,1,profile)== ...
        csr.nwk.controlWireBytes(kind{1},sibling,1,profile), ...
        'autocase:NoPathWirePreflight','A sibling control changed size.');
end
checks(end+1)=checked('other_neighbor_checks_and_sibling_controls_keep_baseline_sizes', ...
    struct('neighbor_subtypes_checked',4,'sibling_control_types_checked',5));
report=struct('schema','csr-no-path-wire-preflight-v1','passed',all([checks.passed]), ...
    'checks',checks,'network_simulation_executed',false,'random_variates_requested',0, ...
    'scope','Public NWK forwarded-DATA rejection and HOP Frames API; native 0-330 s fixture has no NoPath, so network effect is unexercised');
ac.writeJson(fullfile(folder,'no_path_wire_preflight.json'),report);
end
function value=checked(name,details)
value=struct('name',name,'passed',true,'details',details);
end
