function report=relayCustodyPreflight(config,folder)
%RELAYCUSTODYPREFLIGHT Accepted-copy ownership at public NWK/HOP boundaries.
% Runs production and replay-candidate classes independently. No private
% state writes, comparator tolerance changes, or network simulation occurs.
if ~isfolder(folder), mkdir(folder); end
checks=struct('name',{},'passed',{},'details',{});
report=struct('schema','csr-relay-custody-preflight-v1','passed',false, ...
    'completed',false,'checks',checks,'network_simulation_executed',false, ...
    'scope','Real HOP duplicate windows, NWK accepted-copy queue/custody, outgoing HOP sequences, public sink unique-delivery callbacks', ...
    'fixture_limits','Two-copy edge cases use valid test-only HOP NsdpLimit=0. The captured-count case retains NsdpLimit=16 and reproduces 25/26/27 by public inputs. Neither is a replay of captured RF/MAC timing.', ...
    'accounting_scope','Global Simulation statistics and provisional-drop recovery are tested separately by the integrated accounting preflight.');
for candidate=[false true]
    if candidate, prefix='candidate'; else, prefix='production'; end
    runGroup([prefix '_captured_nsdp_25_26_27'],@capturedGate,candidate,16,4,512);
    runGroup([prefix '_ack_duplicate_stays_filtered'],@ackDuplicate,candidate,16,4,512);
    runGroup([prefix '_fifo_distinct_sequences_and_ack_ownership'],@fifoAck,candidate,0,4,512);
    runGroup([prefix '_dack_release_hold_and_new_copy'],@dackRelease,candidate,0,4,512);
    runGroup([prefix '_retry_failure_keeps_sibling'],@failureRelease,candidate,0,4,512);
    runGroup([prefix '_no_ack_sent_releases_only_its_copy'],@noAckRelease,candidate,16,4,512);
    runGroup([prefix '_out_of_order_and_invalid_release_tokens'],@outOfOrder,candidate,0,4,512);
    runGroup([prefix '_upstream_token_replaced'],@upstreamToken,candidate,0,4,512);
    runGroup([prefix '_final_sink_delivers_unique_application_once'],@sinkUnique,candidate,16,2,512);
    runGroup([prefix '_queue_full_rejection_then_same_sequence_retry'],@queueFull,candidate,0,4,1);
    runGroup([prefix '_nested_send_reject_does_not_reset_sibling'],@nestedReject,candidate,0,4,512);
end
report.checks=checks; report.completed=numel(checks)==22;
report.passed=report.completed && all([checks.passed]);
report.attempted_checks=numel(checks); report.passed_checks=sum([checks.passed]);
report.failed_checks=sum(~[checks.passed]);
ac.writeJson(fullfile(folder,'relay_custody_preflight.json'),report);
assert(report.passed,'relaycase:CustodyComponentFailures', ...
    '%d of %d relay custody groups failed. All groups were attempted; inspect relay_custody_preflight.json and public_custody_trace.json.', ...
    report.failed_checks,report.attempted_checks);
    function runGroup(name,callback,candidate,limit,node,queueLimit)
        h=[]; details=struct(); passed=false;
        try
            h=ac.RelayCustodyProbe(config,fullfile(folder,name),candidate,limit,node,queueLimit);
            assert(h.Config.Hop.NsdpLimit==limit && h.Network.NodeId==node && ...
                h.Config.Nwk.QueueLimit==queueLimit,'relaycase:ProbeConfiguration', ...
                'The public component fixture must preserve the requested NSDP, node and queue limits.');
            callback(h); passed=true;
        catch caught
            details.error_identifier=caught.identifier; details.error_message=caught.message;
            details.error_stack=caught.stack;
        end
        if ~isempty(h)
            h.persist(); details.checks=h.Checks; details.final_state=h.snapshot();
        end
        checks(end+1)=struct('name',name,'passed',passed,'details',details); %#ok<AGROW>
        report.checks=checks; ac.writeJson(fullfile(folder,'relay_custody_preflight.json'),report);
        label='FAIL'; if passed, label='PASS'; end
        fprintf('  Relay custody %d/22: %s -- %s\n',numel(checks),name,label);
    end
end
function capturedGate(h)
for k=1:25, h.receive(h.input(7,7000+k,k)); end
app=h.input(7,2873,26);
h.expect('public prefill has 25 accepted source7 copies',h.Network.nsdpCount(app.App)==25 && ...
    h.Network.stats().WaitingForHop==25,h.snapshot(),struct('nsdp',25,'queue',25));
h.receive(app);
h.expect('first DACK-marked copy raises NSDP 25 to 26',h.Network.nsdpCount(app.App)==26 && ...
    strcmp(h.Feedback{end}.Kind,'DACK'),h.snapshot(),struct('nsdp',26,'feedback','DACK'));
h.receive(app);
a=h.Owned{26}; b=h.Owned{27};
h.expect('retry with identical incoming HOP sequence owns a second queue occurrence', ...
    h.Network.nsdpCount(app.App)==27 && h.Network.stats().WaitingForHop==27 && ...
    h.Hop.stats().Duplicates==0 && strcmp(h.Feedback{end}.Kind,'DACK') && ...
    a.Id==b.Id && a.SourceId==b.SourceId && a.NwkCustodyId~=b.NwkCustodyId && ...
    a.NwkCustodyNodeId==4 && b.NwkCustodyNodeId==4, ...
    struct('state',h.snapshot(),'first',a,'second',b), ...
    struct('nsdp',27,'queue',27,'hop_duplicates',0,'distinct_local_custody',true));
end
function ackDuplicate(h)
f=h.input(7,2873,1); h.receive(f); h.receive(f);
h.expect('ACK-marked incoming sequence duplicate never reaches NWK twice', ...
    numel(h.Owned)==1 && h.Network.nsdpCount(f.App)==1 && h.Hop.stats().Duplicates==1 && ...
    h.Network.stats().DuplicateApplications==0,h.snapshot(), ...
    struct('accepted_copies',1,'hop_duplicates',1,'nwk_duplicates',0));
end
function fifoAck(h)
f=h.input(7,2873,1); h.receive(f); h.receive(f); h.receive(h.input(8,3011,2)); h.open();
h.expect('only first FIFO occurrence admitted under initial one-owner HOP capacity', ...
    numel(h.Frames)==1 && h.Frames{1}.App.SourceId==7 && ...
    h.Network.stats().PendingCustody==3 && h.Network.stats().WaitingForHop==2, ...
    h.snapshot(),struct('outgoing',1,'pending_custody',3,'waiting',2));
first=h.Frames{1}; h.feedback(first,'ack');
h.expect('NsdpRelease followed by Terminal removes only first sibling', ...
    h.Network.nsdpCount(f.App)==1 && h.Network.stats().PendingCustody==2, ...
    h.snapshot(),struct('source7_nsdp',1,'pending_custody',2));
h.Network.releaseFromHop(first.App,'stale_ack'); h.Network.release(first.App,'stale_release');
h.Network.terminal(first.App,true,'stale_terminal'); h.feedback(first,'ack'); h.advance(2e-6);
h.expect('stale callbacks cannot release waiting sibling; second source7 owns next sequence', ...
    numel(h.Frames)==2 && h.Frames{2}.App.SourceId==7 && ...
    h.Frames{2}.App.Id==first.App.Id && h.Frames{2}.Sequence~=first.Sequence && ...
    h.Frames{2}.App.NwkCustodyId~=first.App.NwkCustodyId && ...
    h.Network.nsdpCount(f.App)==1 && numel(h.Releases)==1, ...
    h.snapshot(),struct('outgoing',2,'same_application',true,'distinct_sequence_and_copy',true,'source7_nsdp',1));
h.feedback(h.Frames{2},'ack'); h.advance(2e-6);
h.expect('source8 follows both source7 queue occurrences',numel(h.Frames)==3 && ...
    isequal(cellfun(@(x)x.App.SourceId,h.Frames),[7 7 8]), ...
    cellfun(@(x)x.App.SourceId,h.Frames),[7 7 8]);
h.feedback(h.Frames{3},'ack'); h.advance(2e-6);
h.expect('three independent ACK releases drain all custody exactly once', ...
    h.Network.stats().PendingCustody==0 && numel(h.Releases)==3 && numel(h.Terminals)==3, ...
    h.snapshot(),struct('pending_custody',0,'releases',3,'terminals',3));
end
function dackRelease(h)
f=h.input(7,2873,1); h.receive(f); h.receive(f); h.open(); first=h.Frames{1};
h.feedback(first,'dack'); h.feedback(first,'dack');
h.expect('DACK releases first NWK copy once but retains HOP capacity', ...
    h.Network.nsdpCount(f.App)==1 && numel(h.Releases)==1 && ...
    h.Hop.stats().DackHoldCount==1 && h.Hop.PendingDataCount==1, ...
    h.snapshot(),struct('nsdp',1,'releases',1,'dack_holds',1,'pending_hop',1));
h.receive(f);
h.expect('same incoming sequence accepted again after earlier local owner release', ...
    h.Network.nsdpCount(f.App)==2 && numel(h.Owned)==3 && ...
    numel(unique(cellfun(@(x)x.NwkCustodyId,h.Owned)))==3, ...
    h.snapshot(),struct('nsdp',2,'distinct_copies',3));
h.advance(4.01); % MaxResends=0 doubles the configured 2-second DACK hold.
h.expect('DACK expiry releases capacity without releasing either remaining copy', ...
    h.Hop.stats().DackExpired==1 && h.Hop.stats().DackHoldCount==0 && ...
    h.Network.nsdpCount(f.App)==2 && numel(h.Releases)==1 && numel(h.Frames)==2, ...
    h.snapshot(),struct('dack_expired',1,'nsdp',2,'releases',1,'outgoing',2));
h.feedback(h.Frames{2},'ack'); h.advance(2e-6); h.feedback(h.Frames{3},'ack');
h.expect('later copies release independently',h.Network.nsdpCount(f.App)==0 && ...
    numel(h.Releases)==3,h.snapshot(),struct('nsdp',0,'releases',3));
end
function failureRelease(h)
f=h.input(7,2873,1); h.receive(f); h.receive(f); h.open(); first=h.Frames{1};
h.Hop.notifySent(first); h.advance(2.01);
h.expect('terminal retry failure releases only failed owner and admits sibling', ...
    h.Hop.stats().Failed==1 && numel(h.Releases)==1 && numel(h.Terminals)==1 && ...
    h.Network.nsdpCount(f.App)==1 && numel(h.Frames)==2 && ...
    h.Frames{2}.App.NwkCustodyId~=first.App.NwkCustodyId, ...
    h.snapshot(),struct('failed',1,'releases',1,'terminals',1,'nsdp',1,'outgoing',2));
h.Network.releaseFromHop(first.App,'retry_exhausted'); h.Network.terminal(first.App,true,'stale_completion');
h.feedback(first,'ack'); h.Hop.notifySent(first); h.advance(2e-6);
h.expect('late feedback and sent callback cannot release or resurrect retired owner', ...
    h.Network.nsdpCount(f.App)==1 && numel(h.Releases)==1 && h.Hop.PendingDataCount==1, ...
    h.snapshot(),struct('nsdp',1,'releases',1,'pending_hop',1));
h.feedback(h.Frames{2},'ack');
h.expect('surviving sibling completes normally',h.Network.nsdpCount(f.App)==0 && ...
    numel(h.Releases)==2,h.snapshot(),struct('nsdp',0,'releases',2));
end
function outOfOrder(h)
f=h.input(7,2873,1); h.receive(f); h.receive(f); a=h.Owned{1}; b=h.Owned{2};
foreign=b; foreign.NwkCustodyNodeId=8; tokenless=rmfield(b,{'NwkCustodyNodeId','NwkCustodyId'});
wrongApp=b; wrongApp.Id=uint64(9999); pendingTimers=h.Clock.PendingCount;
h.Network.releaseFromHop(foreign,'foreign'); h.Network.release(tokenless,'missing');
h.Network.releaseFromHop(wrongApp,'wrong_application');
h.expect('foreign token, absent token, and wrong application cannot release siblings', ...
    h.Network.nsdpCount(f.App)==2 && h.Clock.PendingCount==pendingTimers, ...
    struct('state',h.snapshot(),'pending_timers',h.Clock.PendingCount), ...
    struct('nsdp',2,'pending_timers',pendingTimers));
h.Network.releaseFromHop(b,'scripted_out_of_order_ack'); h.Network.releaseFromHop(b,'repeated_ack');
h.Network.terminal(b,true,'following_terminal');
h.expect('releasing second occurrence first leaves first occurrence untouched', ...
    h.Network.nsdpCount(f.App)==1,h.snapshot(),struct('nsdp',1));
h.open();
h.expect('remaining first occurrence preserves original ownership', ...
    numel(h.Frames)==1 && h.Frames{1}.App.NwkCustodyId==a.NwkCustodyId, ...
    h.Frames{1}.App,a);
h.feedback(h.Frames{1},'ack');
h.expect('last occurrence releases once',h.Network.nsdpCount(f.App)==0,h.snapshot(),struct('nsdp',0));
end
function upstreamToken(h)
f=h.input(7,2873,1); f.App.NwkCustodyNodeId=8; f.App.NwkCustodyId=uint64(999999);
h.receive(f); h.receive(f); a=h.Owned{1}; b=h.Owned{2};
h.expect('each acceptance replaces inherited upstream ownership with a fresh local token', ...
    a.NwkCustodyNodeId==4 && b.NwkCustodyNodeId==4 && ...
    a.NwkCustodyId~=b.NwkCustodyId && a.NwkCustodyId~=f.App.NwkCustodyId && ...
    a.Id==f.App.Id && b.Id==f.App.Id && a.HopCount==2 && isequal(a.Traversal,[7 8 4]), ...
    struct('incoming',f.App,'first',a,'second',b),struct('local_node',4,'fresh_tokens',true,'application_identity_preserved',true));
end
function sinkUnique(h)
f=h.input(7,2873,1); h.receive(f); h.receive(f); h.advance(10);
late=f; late.Sequence=uint16(2); late.App.NwkCustodyNodeId=4; late.App.NwkCustodyId=uint64(99);
h.receive(late); h.receive(late);
h.expect('final sink counts one application despite same-sequence and late fresh-sequence copies', ...
    numel(h.Delivered)==1 && h.Delivered{1}.Id==f.App.Id && ...
    h.Hop.stats().Duplicates==2 && h.Network.stats().DuplicateApplications==1 && ...
    h.Network.stats().PendingCustody==0,h.snapshot(), ...
    struct('unique_delivery_callbacks',1,'hop_duplicates',2,'nwk_duplicates',1,'pending_custody',0));
end
function queueFull(h)
f=h.input(7,2873,1); h.receive(f); h.receive(f);
h.expect('full queue refuses second copy without creating ownership',numel(h.Owned)==1 && ...
    h.Network.nsdpCount(f.App)==1 && h.Hop.stats().CustodyRefused==1 && ...
    h.Network.stats().QueueAdmissionRejections==1,h.snapshot(), ...
    struct('accepted_copies',1,'nsdp',1,'custody_refused',1,'queue_rejected',1));
h.Network.releaseFromHop(h.Owned{1},'fixture_capacity_release'); h.receive(f);
h.expect('refused HOP sequence remains retryable after capacity release',numel(h.Owned)==2 && ...
    h.Network.nsdpCount(f.App)==1 && h.Owned{2}.NwkCustodyId~=h.Owned{1}.NwkCustodyId, ...
    h.snapshot(),struct('accepted_copies',2,'nsdp',1,'fresh_token',true));
end
function nestedReject(h)
f=h.input(7,2873,1); h.receive(f); first=h.Owned{1};
h.ReentryFrame=f; h.ReenterOnSend=true; h.open();
h.expect('nested public callback releases old copy and accepts sibling before rejected send returns', ...
    numel(h.Owned)==2 && h.Network.nsdpCount(f.App)==1 && ...
    h.Network.stats().WaitingForHop==1 && isempty(h.Frames),h.snapshot(), ...
    struct('accepted_copies',2,'nsdp',1,'waiting',1,'outgoing',0));
h.open();
h.expect('old send return cannot reset or submit the newly accepted sibling under old token', ...
    numel(h.Frames)==1 && h.Frames{1}.App.NwkCustodyId==h.Owned{2}.NwkCustodyId && ...
    h.Frames{1}.App.NwkCustodyId~=first.NwkCustodyId && h.Network.stats().WaitingForHop==0, ...
    h.snapshot(),struct('outgoing',1,'new_token',true,'waiting',0));
end

function noAckRelease(h)
f=h.input(7,2873,1); f.AckRequired=false; f.App.AckRequired=false;
h.receive(f); second=f; second.Sequence=uint16(2); h.receive(second); h.open();
h.expect('two distinct incoming no-ACK copies both submit without HOP owners', ...
    numel(h.Frames)==2 && h.Network.nsdpCount(f.App)==2 && h.Hop.PendingDataCount==0 && ...
    ~h.Frames{1}.AckRequired && ~h.Frames{2}.AckRequired, ...
    h.snapshot(),struct('outgoing',2,'nsdp',2,'pending_hop',0,'ack_required',false));
h.Hop.notifySent(h.Frames{1}); h.Hop.notifySent(h.Frames{1});
h.Network.terminal(h.Frames{1}.App,true,'repeated_no_ack_terminal');
h.expect('direct no-ACK terminal and repeated old callbacks retain sibling', ...
    h.Network.nsdpCount(f.App)==1 && isempty(h.Releases), ...
    h.snapshot(),struct('nsdp',1,'hop_nsdp_release_callbacks',0));
h.Hop.notifySent(h.Frames{2}); h.advance(2e-6);
h.expect('second no-ACK sent indication releases final independent copy', ...
    h.Network.nsdpCount(f.App)==0 && h.Network.stats().PendingCustody==0 && ...
    numel(h.Frames)==2,h.snapshot(),struct('nsdp',0,'pending_custody',0,'outgoing',2));
end
