function summary = campusReleaseContract(directory,root,snapshot,sourceSnapshotSHA256)
%CAMPUSRELEASECONTRACT Execute and export the exact original campus benchmark.
% No observer, injected timing policy, shortened horizon or post-stop drain.
[item,~]=csr.scenario.tranche17Suite();
caseDirectory=fullfile(directory,item.StorageKey);
if isfolder(caseDirectory)
    error('csr:t17:IncompleteStage','Campus output already exists; restart in a new output directory.');
end
fprintf('Starting campus_multihop_6000: seed 128, 6000 simulated seconds, default continuous timing.\n');
fprintf('This long phase may take hours. It schedules no progress callbacks; elapsed time prints when the run returns.\n');
fprintf('Started UTC: %s\n',csr.validation.Artifacts.utcNow());
clock=tic;
simulation=csr.sim.NetworkSimulation(item.Config);
result=simulation.run();
elapsed=toc(clock);
fprintf('Campus simulation returned after %.1f elapsed minutes; checking and exporting evidence.\n',elapsed/60);
if simulation.Scheduler.Now~=6000 || ~isequal(result.Config,item.Config)
    error('csr:t17:CampusCompletion','Campus must complete normally at the unchanged 6000-second horizon.');
end
if ~strcmp(result.Metadata.Backend,'portable') || ...
        ~strcmp(result.Metadata.ChannelModel,'csr-phy') || ...
        ~strcmp(result.Metadata.ModelStage,'tranche-3-autonomous-network-routing') || ...
        isfield(result,'TransportTiming') || isfield(result,'LinkDiagnostics') || ...
        isfield(result,'ServiceDiagnostics')
    error('csr:t17:CampusMode','Expected real PHY, autonomous routing and uninstrumented default timing.');
end
% Existing summaries enforce identity, per-node totals, ownership bounds,
% admission counters (including omitted prefix records), and complete traces.
[performance,applications]=csr.analysis.performanceSummary(result);
for trace={result.ProtocolTrace,result.PhyTrace}
    times=trace{1}.TimeSeconds;
    if any(~isfinite(times) | times<0 | times>6000) || any(diff(times)<0)
        error('csr:t17:Trace','Protocol and PHY traces must be ordered and contained in the fixed horizon.');
    end
end
rawDirectory=fullfile(caseDirectory,'raw');
[row,~]=csr.validation.exportResearchCase(result,rawDirectory,root,snapshot, ...
    fullfile(root,item.ScenarioFile));
analysisDirectory=fullfile(caseDirectory,'analysis'); mkdir(analysisDirectory);
writetable(struct2table(performance,'AsArray',true),fullfile(analysisDirectory,'performance_summary.csv'));
writetable(applications,fullfile(analysisDirectory,'applications.csv'));
sourceFile=fullfile(rawDirectory,'protocol_trace.csv');
aggregateOptions=struct('Scenario',item.Scenario,'BucketWidthSeconds',item.BucketWidthSeconds, ...
    'SourceFile','raw/protocol_trace.csv','SourceFileSHA256',csr.validation.Artifacts.sha256(sourceFile), ...
    'ScenarioSHA256',item.ScenarioSHA256,'ProfileID',item.ProfileId, ...
    'SourceSnapshotSHA256',sourceSnapshotSHA256);
[series,provenance]=csr.analysis.benchmarkAggregates(result,aggregateOptions);
aggregateFile=fullfile(analysisDirectory,'aggregates.csv');
writetable(series,aggregateFile);
provenance.output=struct('path','analysis/aggregates.csv', ...
    'sha256',csr.validation.Artifacts.sha256(aggregateFile));
csr.validation.Artifacts.writeJson(fullfile(analysisDirectory,'aggregate_provenance.json'),provenance);
files=csr.validation.Artifacts.fileInventory(caseDirectory);
local=endsWith({files.path},'.mat');
manifest=struct('schema','csr-matlab-benchmark-case-v1','status','completed', ...
    'case_id',item.CaseId,'scenario',item.Scenario,'scenario_sha256',item.ScenarioSHA256, ...
    'profile_id',item.ProfileId,'source_kind',item.SourceKind, ...
    'ns3_source_commit',result.Metadata.SourceCommit,'matlab_version',version, ...
    'matlab_release',version('-release'),'runtime',csr.sim.capabilities(), ...
    'duration_s',item.DurationSeconds,'seed',item.Seed,'bucket_width_s',item.BucketWidthSeconds, ...
    'opnet_available',item.OpnetAvailable,'reference_directory',item.ReferenceDirectory, ...
    'source_files',snapshot,'source_snapshot_sha256',sourceSnapshotSHA256, ...
    'structural_checks_passed',true,'numerical_parity_established',false, ...
    'admission_trace_omitted_records',result.Statistics.OmittedApplicationAdmissionRecords, ...
    'admission_counts_complete',true,'files',files(~local),'local_files',files(local));
manifestPath=fullfile(caseDirectory,'benchmark_manifest.json');
csr.validation.Artifacts.writeJson(manifestPath,manifest);
row.CaseId=item.CaseId; row.SourceKind=item.SourceKind;
row.Attempts=sum(result.ApplicationAdmissionStatistics.Attempts);
row.AdmissionBlocked=row.Attempts-row.Generated;
row.OmittedApplicationAdmissionRecords=result.Statistics.OmittedApplicationAdmissionRecords;
writetable(struct2table(row,'AsArray',true),fullfile(directory,'benchmark_summary.csv'));
summary=struct('Schema','csr-tranche17-campus-release-summary-v1', ...
    'CaseId',item.CaseId,'StorageKey','c','CompletedCaseCount',1, ...
    'DurationSeconds',6000,'SchedulerStopSeconds',simulation.Scheduler.Now,'Seed',128, ...
    'StructuralChecksPassed',true,'DefaultContinuousTiming',true, ...
    'RealPHY',true,'AutonomousRouting',true,'PostHorizonDrain',false, ...
    'AcceptanceEstablished',false,'NumericalParityEstablished',false, ...
    'Performance',performance,'Admissions',struct('Attempts',row.Attempts, ...
        'Admitted',row.Generated,'Blocked',row.AdmissionBlocked, ...
        'TraceRecords',height(result.ApplicationAdmissionTrace), ...
        'OmittedTraceRecords',row.OmittedApplicationAdmissionRecords,'CountsComplete',true), ...
    'ProtocolTraceOmissions',result.Statistics.OmittedTraceRecords, ...
    'PhyTraceOmissions',result.Statistics.OmittedPhyTraceRecords, ...
    'FiniteStopPendingIsFailure',false,'ElapsedWallSeconds',elapsed, ...
    'Case',struct('CaseId',item.CaseId,'Directory','campus/c', ...
        'ManifestSHA256',csr.validation.Artifacts.sha256(manifestPath)));
csr.validation.Artifacts.checkSnapshot(root,snapshot);
csr.validation.Artifacts.writeJson(fullfile(directory,'summary.json'),summary);
fprintf('Campus exported: %d delivered, %d dropped, %d pending of %d admitted applications.\n', ...
    row.Received,row.Dropped,row.Pending,row.Generated);
fprintf('Admission trace: %d retained and %d explicitly omitted; complete counters retained.\n', ...
    height(result.ApplicationAdmissionTrace),row.OmittedApplicationAdmissionRecords);
end
