function summary = ensembleContract(directory,caseId,root,snapshot,sourceSnapshotSHA256)
%ENSEMBLECONTRACT Full-campus unchanged-default seed comparison.
% The checkpoint helper creates the stage directory and start receipt first.
% There are no observers, progress callbacks, shortened inputs or post-stop drain.
[cases,plan]=csr.scenario.tranche25Suite();
selected=find(strcmp({cases.CaseId},caseId));
if numel(selected)~=1
    error('csr:t25:Case','Expected one planned seed case.');
end
item=cases(selected);
entries=dir(directory); entries=entries(~ismember({entries.name},{'.','..'}));
if ~isfolder(directory) || ~isequal({entries.name},{'start.json'})
    error('csr:t25:IncompleteStage','The case requires a fresh stage containing only start.json.');
end
fprintf('Starting %s: %s, seed %d, complete 6000-second original campus.\n',caseId,item.Policy,item.Config.Seed);
fprintf('No progress callbacks are scheduled. Started UTC: %s\n',csr.validation.Artifacts.utcNow());
completedResult=false; runClock=tic;
try
    simulation=csr.sim.NetworkSimulation(item.Config);
    result=simulation.run(); completedResult=true; elapsed=toc(runClock);
    fprintf('Case %s returned after %.1f minutes; checking and exporting evidence.\n',caseId,elapsed/60);
    if simulation.Scheduler.Now~=6000 || ~isequaln(result.Config,item.Config)
        error('csr:t25:CampusCompletion','The case must complete at the unchanged 6000-second horizon.');
    end
    if ~strcmp(result.Metadata.Backend,'portable') || ...
            ~strcmp(result.Metadata.ChannelModel,'csr-phy') || ...
            ~strcmp(result.Metadata.ModelStage,'tranche-3-autonomous-network-routing') || ...
            any(isfield(result,{'TransportTiming','LinkDiagnostics','ServiceDiagnostics'}))
        error('csr:t25:CampusMode','Expected real PHY, autonomous routing and uninstrumented continuous timing.');
    end
    [performance,applications]=csr.analysis.performanceSummary(result);
    for trace={result.ProtocolTrace,result.PhyTrace,result.ApplicationAdmissionTrace}
        times=trace{1}.TimeSeconds;
        if any(~isfinite(times) | times<0 | times>6000) || any(diff(times)<0)
            error('csr:t25:Trace','Trace times must be ordered and inside the fixed horizon.');
        end
    end
    statistics=result.Statistics;
    attempts=sum(result.ApplicationAdmissionStatistics.Attempts);
    if statistics.OmittedTraceRecords~=0 || statistics.OmittedPhyTraceRecords~=0 || ...
            attempts~=plan.expected_admission_attempts || ...
            height(result.ApplicationAdmissionTrace)~=100000 || ...
            statistics.OmittedApplicationAdmissionRecords~=attempts-100000
        error('csr:t25:Trace','Complete protocol/PHY traces and the original admission-prefix accounting are required.');
    end
    rawDirectory=fullfile(directory,'raw');
    [row,rawManifest]=csr.validation.exportResearchCase(result,rawDirectory,root,snapshot, ...
        fullfile(root,item.ScenarioFile));
    rawManifest.imported_seed=128;
    rawManifest.seed_override_after_import=true;
    rawManifest.comparison_scope=['Original seed 128 MATLAB CSV imported, then only Config.Seed overridden. ' ...
        'Native reference uses separately hashed seed-specific input; no common-RNG claim.'];
    csr.validation.Artifacts.writeJson(fullfile(rawDirectory,'case_manifest.json'),rawManifest);
    analysisDirectory=fullfile(directory,'analysis'); mkdir(analysisDirectory);
    writetable(stableText(struct2table(performance,'AsArray',true)), ...
        fullfile(analysisDirectory,'performance_summary.csv'));
    writetable(stableText(applications),fullfile(analysisDirectory,'applications.csv'));
    aggregateOptions=struct('Scenario',item.Scenario,'BucketWidthSeconds',item.BucketWidthSeconds, ...
        'SourceFile','raw/protocol_trace.csv', ...
        'SourceFileSHA256',csr.validation.Artifacts.sha256(fullfile(rawDirectory,'protocol_trace.csv')), ...
        'ScenarioSHA256',item.ScenarioSHA256,'ProfileID',item.ProfileId, ...
        'SourceSnapshotSHA256',sourceSnapshotSHA256);
    [series,provenance]=csr.analysis.benchmarkAggregates(result,aggregateOptions);
    aggregateFile=fullfile(analysisDirectory,'aggregates.csv');
    writetable(stableText(series),aggregateFile);
    provenance.output=struct('path','analysis/aggregates.csv', ...
        'sha256',csr.validation.Artifacts.sha256(aggregateFile));
    csr.validation.Artifacts.writeJson(fullfile(analysisDirectory,'aggregate_provenance.json'),provenance);
    row.CaseId=caseId; row.SourceKind=item.SourceKind; row.Policy=item.Policy;
    row.Attempts=attempts; row.AdmissionBlocked=attempts-row.Generated;
    row.OmittedApplicationAdmissionRecords=statistics.OmittedApplicationAdmissionRecords;
    writetable(stableText(struct2table(row,'AsArray',true)),fullfile(directory,'benchmark_summary.csv'));
    files=csr.validation.Artifacts.fileInventory(directory,{'start.json'});
    local=endsWith({files.path},'.mat') | endsWith({files.path},'.zip');
    manifest=struct('schema','csr-tranche25-ensemble-case-v1','status','completed', ...
        'case_id',caseId,'policy',item.Policy,'original_case_id',item.OriginalCaseId, ...
        'case',item.PlanEntry,'scenario',item.Scenario,'scenario_sha256',item.ScenarioSHA256, ...
        'profile_id',item.ProfileId,'source_kind',item.SourceKind, ...
        'ns3_source_commit',result.Metadata.SourceCommit,'matlab_version',version, ...
        'matlab_release',version('-release'),'runtime',csr.sim.capabilities(), ...
        'result_metadata',result.Metadata,'duration_s',6000,'scheduler_stop_s',simulation.Scheduler.Now, ...
        'seed',item.Config.Seed,'imported_seed',128,'seed_override_after_import',true,'bucket_width_s',item.BucketWidthSeconds,'mode','continuous', ...
        'observer_enabled',false,'post_horizon_drain',false, ...
        'opnet_available',item.OpnetAvailable,'opnet_scope','archived-seed128-aggregate-context-only', ...
        'opnet_same_seed_reference_available',false,'reference_directory',item.ReferenceDirectory, ...
        'source_files',snapshot,'source_snapshot_sha256',sourceSnapshotSHA256, ...
        'structural_checks_passed',true,'data_drained',row.DataDrained, ...
        'numerical_parity_established',false,'admission_counts_complete',true, ...
        'original_admission_trace_prefix',true, ...
        'admission_trace_omitted_records',statistics.OmittedApplicationAdmissionRecords, ...
        'files',files(~local),'local_files',files(local));
    manifestPath=fullfile(directory,'case.json');
    csr.validation.Artifacts.writeJson(manifestPath,manifest);
    summary=struct('Schema','csr-tranche25-ensemble-summary-v1', ...
        'CaseId',caseId,'Policy',item.Policy,'OriginalBenchmarkCaseId',item.OriginalCaseId, ...
        'CompletedCaseCount',1,'DurationSeconds',6000,'SchedulerStopSeconds',simulation.Scheduler.Now, ...
        'Seed',item.Config.Seed,'ImportedSeed',128,'SeedOverrideAfterImport',true,'StructuralChecksPassed',true,'DefaultContinuousTiming',true, ...
        'RealPHY',true,'AutonomousRouting',true,'ObserverEnabled',false,'PostHorizonDrain',false, ...
        'RequestedPolicySameAsDefault',strcmp(item.Policy,'actual-tx'), ...
        'OriginalAdmissionTracePrefix',true,'AcceptanceEstablished',false, ...
        'NumericalParityEstablished',false,'Performance',performance, ...
        'Admissions',struct('Attempts',attempts,'Admitted',row.Generated,'Blocked',row.AdmissionBlocked, ...
            'TraceRecords',height(result.ApplicationAdmissionTrace), ...
            'OmittedTraceRecords',statistics.OmittedApplicationAdmissionRecords,'CountsComplete',true), ...
        'ProtocolTraceOmissions',statistics.OmittedTraceRecords, ...
        'PhyTraceOmissions',statistics.OmittedPhyTraceRecords,'FiniteStopPendingIsFailure',false, ...
        'ElapsedWallSeconds',elapsed, ...
        'Case',struct('CaseId',caseId,'Directory',caseId, ...
            'ManifestSHA256',csr.validation.Artifacts.sha256(manifestPath)));
    csr.validation.Artifacts.checkSnapshot(root,snapshot);
    csr.validation.Artifacts.writeJson(fullfile(directory,'summary.json'),summary);
    fprintf('%s exported: %d delivered, %d dropped, %d pending of %d admitted.\n', ...
        caseId,row.Received,row.Dropped,row.Pending,row.Generated);
catch failure
    if completedResult && ~isfile(fullfile(directory,'raw','summary.json'))
        try
            csr.analysis.exportResults(result,fullfile(directory,'partial_raw'));
        catch exportFailure
            try
                csr.validation.Artifacts.writeJson(fullfile(directory,'partial.json'), ...
                    struct('Metadata',result.Metadata,'Statistics',result.Statistics, ...
                    'ExportFailure',struct('Identifier',exportFailure.identifier,'Message',exportFailure.message)));
            catch
                % Retain the original simulation/check failure on a full disk.
            end
        end
    end
    try
        csr.validation.Artifacts.writeJson(fullfile(directory,'failure.json'), ...
            struct('Identifier',failure.identifier,'Message',failure.message,'CaseId',caseId,'Stack',failure.stack));
    catch
        % Do not replace the original failure with an output-device exception.
    end
    rethrow(failure);
end
end

function value=stableText(value)
for name=value.Properties.VariableNames
    column=value.(name{1});
    if ischar(column), value.(name{1})=string(cellstr(column));
    elseif iscellstr(column), value.(name{1})=string(column); end %#ok<ISCLSTR>
end
end
