function report = lossTimingContract(outputDirectory)
%LOSSTIMINGCONTRACT Paired controlled-loss runs using identical prescribed inputs.
if nargin<1, outputDirectory = ''; end
root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
planPath = fullfile(root,'scenarios','t15','plan.json');
plan = jsondecode(fileread(planPath));
if ~strcmp(plan.schema,'csr-tranche15-loss-timing-input-v1') || ...
        ~isequal(string(plan.modes(:)),["continuous";"nanoseconds"]) || ...
        ~isequal(string(plan.cases(:)),["ok";"data";"ack";"out"]) || ...
        plan.case_count_per_mode~=4 || plan.total_case_count~=8 || ...
        plan.duration_seconds~=64 || plan.checkpoint_count_per_mode~=264 || ...
        plan.total_checkpoint_count~=528
    error('csr:validation:LossTimingPlan','The paired timing plan is unsupported.');
end
continuousDirectory = ''; nanosecondsDirectory = '';
if ~isempty(outputDirectory)
    continuousDirectory = fullfile(outputDirectory,'c');
    nanosecondsDirectory = fullfile(outputDirectory,'n');
end
continuous = csr.validation.lossTimingRun(continuousDirectory,'continuous');
nanoseconds = csr.validation.lossTimingRun(nanosecondsDirectory,'nanoseconds');
fields = {'Events','Draws','Usage','Checkpoints','Transport','Terminals','Timing','Precision'};
continuousSummary = rmfield(continuous,fields); nanosecondsSummary = rmfield(nanoseconds,fields);
shapeMatches = continuous.CaseCount==plan.case_count_per_mode && ...
    nanoseconds.CaseCount==plan.case_count_per_mode && ...
    continuous.CheckpointCount==plan.checkpoint_count_per_mode && ...
    nanoseconds.CheckpointCount==plan.checkpoint_count_per_mode && ...
    strcmp(continuous.TimingMode,'continuous') && strcmp(nanoseconds.TimingMode,'nanoseconds') && ...
    isequal(string({continuous.CaseResults.Case})',string(plan.cases(:))) && ...
    isequal(string({nanoseconds.CaseResults.Case})',string(plan.cases(:)));
report = struct('Schema','csr-tranche15-loss-timing-contract-v1', ...
    'ShapeMatchesPlan',shapeMatches, ...
    'DiagnosticCompleted',shapeMatches && continuous.DiagnosticCompleted && nanoseconds.DiagnosticCompleted, ...
    'Passed',shapeMatches && continuous.Passed && nanoseconds.Passed,'NumericalParityEstablished',false, ...
    'ModeCount',2,'CaseCount',continuous.CaseCount+nanoseconds.CaseCount, ...
    'CheckpointCount',continuous.CheckpointCount+nanoseconds.CheckpointCount, ...
    'FailedCount',continuous.FailedCount+nanoseconds.FailedCount, ...
    'ContinuousSummary',continuousSummary,'NanosecondsSummary',nanosecondsSummary, ...
    'PlanSHA256',csr.validation.Artifacts.sha256(planPath), ...
    'Scope',plan.scope,'Runtime',version, ...
    'ComparisonScope','Both branches retain the original 1 ns legacy comparisons; exact seconds and hex are separate observed evidence. No startup shift or production policy is applied.');
if ~isempty(outputDirectory)
    if ~isfolder(outputDirectory), mkdir(outputDirectory); end
    csr.validation.Artifacts.writeJson(fullfile(outputDirectory,'summary.json'),report);
end
report.Continuous = continuous; report.Nanoseconds = nanoseconds;
end
