#!/usr/bin/env python3
"""Create audited test-only adapters; never edit the accepted +csr tree."""
import argparse, hashlib, json, difflib
from pathlib import Path


def replace_once(text, old, new):
    assert text.count(old) == 1, (old[:80], text.count(old))
    return text.replace(old, new)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--core", type=Path, required=True)
    args = p.parse_args()
    out = Path(__file__).resolve().parent / "+receiver_replay"
    provenance = []
    for relative, name in [("+csr/+phy/SignalEngine.m", "SignalEngine"),
                           ("+csr/+phy/Model.m", "Model"),
                           ("+csr/+mac/Layer.m", "MacLayer")]:
        original = (args.core / relative).read_text()
        result = original
        if name == "SignalEngine":
            result = replace_once(result, "        Config\n", "        Config\n        ReplayDrawTape\n")
            result = replace_once(result, "        function count=get.ActiveSignalCount(obj)", METHODS + "\n        function count=get.ActiveSignalCount(obj)")
            result = replace_once(result,
                "            if incoming.FrontEnd.ChannelMatched\n",
                "            if incoming.FrontEnd.ChannelMatched\n")
            begin = "                threshold=profile.SyncSnrThresholdDb;\n"
            end = "                incoming.SyncEligible=obj.signalSnr(incoming)>=threshold;"
            a, b = result.index(begin), result.index(end)
            result = result[:a] + "                threshold=incoming.ReplaySyncThresholdDb;\n" + result[b:]
            result = replace_once(result,
                "            if ~isempty(obj.TransportTiming)\n                preambleCallback=incoming.CallbackPreambleEndSec; endCallback=incoming.CallbackEndSec;\n",
                "            if isfield(incoming,'CallbackEndSec')\n                preambleCallback=incoming.CallbackPreambleEndSec; endCallback=incoming.CallbackEndSec;\n")
            result = replace_once(result,
                "                allocated=csr.phy.Model.allocateErrors(",
                "                obj.ReplayDrawTape.beginInterval(signal.Id,signal.IntervalStartSec,stop);\n                allocated=receiver_replay.Model.allocateErrors(")
            result = replace_once(result,
                "signal.Frame.RateKeyKbps,interval,obj.Streams.get(obj.Receivers(index).Id,'phy'));",
                "signal.Frame.RateKeyKbps,interval,obj.ReplayDrawTape);")
        elif name == "Model":
            result = result.replace("csr.phy.Model", "receiver_replay.Model")
            result = replace_once(result,
                "            if ~isa(stream, 'RandStream') && ~isa(stream, 'function_handle')",
                "            if ~isa(stream, 'RandStream') && ~isa(stream, 'function_handle') && ~isa(stream,'receiver_replay.DrawTape')")
            result = replace_once(result,
                "                headerErrors = receiver_replay.Model.drawBinomial( ...\n                    headerCount, values.HeaderBer, stream);\n                payloadErrors = receiver_replay.Model.drawBinomial( ...\n                    payloadCount, values.PayloadBer, stream);",
                "                if isa(stream,'receiver_replay.DrawTape')\n                    headerErrors=stream.draw('header',headerCount,values.HeaderBer);\n                    payloadErrors=stream.draw('payload',payloadCount,values.PayloadBer);\n                else\n                    headerErrors = receiver_replay.Model.drawBinomial( ...\n                        headerCount, values.HeaderBer, stream);\n                    payloadErrors = receiver_replay.Model.drawBinomial( ...\n                        payloadCount, values.PayloadBer, stream);\n                end")
        else:
            result = replace_once(result, "classdef Layer < handle", "classdef MacLayer < handle")
            result = replace_once(result, "function obj = Layer(", "function obj = MacLayer(")
            result = replace_once(result, "        InReceiverUpdate = false", "        InReceiverUpdate = false\n        ReplayQueuesEmptyAtEnd = true")
            result = replace_once(result, "        function count = get.DataQueueCount(obj)", MAC_METHODS + "\n        function count = get.DataQueueCount(obj)")
            result = replace_once(result,
                "            obj.FinishEvent = uint64(0);\n            obj.setState('Search');\n",
                "            obj.FinishEvent = uint64(0);\n            obj.setState('Search');\n            if ~obj.ReplayQueuesEmptyAtEnd, return; end\n")
        result = "% TEST-ONLY COPY. Generated by generate_copies.py; accepted core is unchanged.\n" + result
        target = out / (name + ".m")
        target.write_text(result)
        (out / (name + ".patch")).write_text("".join(difflib.unified_diff(original.splitlines(True), result.splitlines(True), fromfile=relative, tofile="+receiver_replay/" + name + ".m")))
        provenance.append({"source": relative, "source_sha256": hashlib.sha256(original.encode()).hexdigest(), "copy": "+receiver_replay/"+name+".m", "copy_sha256": hashlib.sha256(result.encode()).hexdigest()})
    (out.parent / "adapter_provenance.json").write_text(json.dumps(provenance, indent=2)+"\n")


METHODS = r'''        function setReplayDrawTape(obj,tape)
            if ~isa(tape,'receiver_replay.DrawTape'), error('receiver_replay:DrawTape','Expected DrawTape.'); end
            obj.ReplayDrawTape=tape;
        end
        function replaySignal(obj,frame,input)
            % Channel-boundary input only. Acquisition and decoding are untouched.
            index=obj.nodeIndex(input.receiver);
            front=struct('Closure',true,'ChannelMatched',logical(input.channel_matched),'PathModel','recorded_native', ...
                'DistanceMeters',input.distance_m,'PathlossDb',input.tx_dbm-input.rx_dbm, ...
                'ReceivedPowerWatts',csr.phy.Model.dbmToWatts(input.rx_dbm), ...
                'ReceivedPowerDbm',input.rx_dbm,'BackgroundNoiseWatts',input.noise_watts);
            signal=struct('Id',input.signal_id,'Frame',frame,'FrontEnd',front, ...
                'StartSec',input.start_s,'EndSec',input.end_s, ...
                'PreambleEndSec',input.preamble_end_s,'PreambleBits',input.preamblebits, ...
                'PacketBits',input.packetbits,'IntervalStartSec',obj.Scheduler.Now,'IntervalCount',0, ...
                'DecisionSameRate',false,'DecisionJsrDb',-Inf,'DecisionTimeOffset',0, ...
                'HasHighRatePayloadJammer',false,'Allocation',obj.emptyAllocation(), ...
                'NoiseIds',[],'NoiseWatts',[],'SyncEligible',false,'PreambleActive',true, ...
                'Rejected',false,'RejectedDuringTrack',false,'Tracked',false,'Collided',false, ...
                'MissedByState',false,'HalfDuplex',false,'CollisionCount',0,'CaptureCount',0, ...
                'SameRateInterference',false,'JsrDb',-Inf,'TimeOffsetSeconds',0, ...
                'CallbackPreambleEndSec',input.preamble_end_ns/1e9, ...
                'CallbackEndSec',input.end_ns/1e9,'ReplaySyncThresholdDb',input.sync_threshold_db);
            obj.Outstanding=obj.Outstanding+1;
            obj.beginSignal(index,signal);
        end
        function replayOwnTx(obj,nodeId,endSeconds)
            % Same half-duplex bookkeeping as transmit(), with no channel fanout.
            index=obj.nodeIndex(nodeId); now=obj.Scheduler.Now;
            if strcmp(obj.Receivers(index).State,'Tx') && obj.Receivers(index).TxUntil>now
                error('receiver_replay:OverlappingOwnTx','Recorded own transmissions overlap.');
            end
            obj.cancelAcquisition(index);
            for k=1:numel(obj.Receivers(index).Signals)
                active=obj.Receivers(index).Signals{k}; active.HalfDuplex=true;
                obj.Receivers(index).Signals{k}=active;
            end
            previous=obj.Receivers(index).State;
            obj.Receivers(index).State='Tx'; obj.Receivers(index).TxUntil=endSeconds;
            if obj.Receivers(index).TxEvent~=0, obj.Scheduler.cancel(obj.Receivers(index).TxEvent); end
            obj.Receivers(index).TxEvent=obj.Scheduler.scheduleAt(endSeconds,@()obj.finishTx(index));
            obj.notifyState(index,previous);
        end'''

MAC_METHODS = r'''        function replayOwnTx(obj,frame,endSeconds,queuesEmpty,activeNodes)
            % Test-only replacement for the external TX start, preserving the
            % real MAC post-transmit wait/finish logic and PHY callback order.
            obj.PreparationActive=false;
            obj.ReplayQueuesEmptyAtEnd=logical(queuesEmpty);
            obj.Config.ActiveNodes=double(activeNodes);
            obj.cancelPostTxWait(); obj.cancelTimer('SleepEvent');
            obj.State='Tx';
            obj.emit('mac_state',frame,struct('State','Tx'));
            obj.Callbacks.Transmit(frame,endSeconds-obj.Scheduler.Now);
            obj.FinishEvent=obj.Scheduler.scheduleAt(endSeconds,@()obj.finishTx());
        end
        function replayPrep(obj,value)
            % Queue/service readiness is a captured external MAC control input.
            % The receiver still makes its own Search/Idle/Track decisions.
            obj.PreparationActive=logical(value);
            if obj.PreparationActive, obj.cancelTimer('SleepEvent'); end
        end
        function replayCancelPostTx(obj)
            obj.cancelPostTxWait();
        end'''

if __name__ == "__main__":
    main()
