function report = probePacketTransport()
%PROBEPACKETTRANSPORT Exercise actual R2026a packet distribution and channel.
% Completion certifies only this controlled native lifecycle on this runtime.
% This function never constructs CSR Simulation or the portable SignalEngine.
csr.sim.native.requireAvailable();
simulator = wirelessNetworkSimulator.init;
radio = struct('CenterFrequencyHz', 915e6, 'BandwidthHz', 1e6, ...
    'TxPowerDbm', 20, 'RateKeyKbps', 8, 'Preamble', 'short', ...
    'EnvelopeProfile', 'bare');
tx = csr.sim.native.PacketNode(2^24-2, [0 0 0], radio);
rx = csr.sim.native.PacketNode(2^24-3, [300 0 0], radio);
overhearer = csr.sim.native.PacketNode(42, [600 0 0], radio);
otherRadio = radio;
otherRadio.CenterFrequencyHz = 920e6;
offChannel = csr.sim.native.PacketNode(43, [300 0 0], otherRadio);
flow = struct('SourceId', tx.CsrId, 'DestinationId', rx.CsrId, ...
    'ApplicationPayloadBytes', 64);
first = csr.packet(uint64(1), flow, 0.1, radio);
secondRadio = radio;
secondRadio.RateKeyKbps = 500;
second = csr.packet(uint64(2), flow, 0.3, secondRadio);
tx.queueFrame(first, 0.1);
tx.queueFrame(second, 0.3);
addNodes(simulator, [tx rx overhearer offChannel]);
lossDb = 50;
speedMps = 299792458;
addChannelModel(simulator, @(info, frame) ...
    csr.sim.native.fixedProbeChannel(info, frame, lossDb, speedMps));
actionCount = 0;
scheduleAction(simulator, @observe, [], 0.05);
cancelled = scheduleAction(simulator, @observe, [], 0.06);
cancelAction(simulator, cancelled);
run(simulator, 0.5);
assert(actionCount == 1, 'csr:sim:NativeProbeAction', ...
    'Scheduled action/cancellation probe failed.');
assert(tx.NumPacketsTransmitted == 2 && tx.NumPacketsPushed == 0, ...
    'csr:sim:NativeProbeTransmit', 'Expected two native transmissions.');
assert(rx.NumPacketsPushed == 2 && rx.NumPacketsCompleted == 2 && ...
    overhearer.NumPacketsPushed == 2 && overhearer.NumPacketsCompleted == 2, ...
    'csr:sim:NativeProbeReceive', ...
    'Native receiver and overhearer must each process two packets.');
assert(offChannel.NumPacketsPushed == 0, 'csr:sim:NativeProbeRelevance', ...
    'The off-channel node unexpectedly received a packet.');
frames = {first, second};
starts = [0.1 0.3];
for node = [rx overhearer]
    delay = norm(node.Position-tx.Position)/speedMps;
    for index = 1:2
        completed = node.Completed(index);
        frame = frames{index};
        expectedEnd = starts(index) + delay + csr.phy.airtime( ...
            frame.WirePayloadBytes, frame.RateKeyKbps, frame.Preamble);
        assert(isequal(completed.Packet.Data.CSRFrame, frame), ...
            'csr:sim:NativeProbeEnvelope', ...
            'CSR frame or 24-bit node IDs changed in the native wrapper.');
        assert(completed.Packet.TransmitterID == tx.ID && ...
            completed.Packet.Power == radio.TxPowerDbm-lossDb && ...
            completed.Packet.DirectToDestination == 0 && ...
            completed.Packet.Abstraction, ...
            'csr:sim:NativeProbeChannel', ...
            'Native channel/wrapper fields differ from the controlled fixture.');
        assert(abs(completed.CompletedSeconds-expectedEnd) < 1e-12, ...
            'csr:sim:NativeProbeTiming', ...
            'Native completion does not include CSR airtime and propagation.');
    end
end
report = struct('Status', 'passed', 'MatlabVersion', version, ...
    'MatlabRelease', version('-release'), ...
    'Scope', ['Controlled native packet/channel lifecycle only; ' ...
    'not integrated CSR PHY/MAC or backend parity.'], ...
    'Transmitter', tx.statistics(), 'Receiver', rx.statistics(), ...
    'Overhearer', overhearer.statistics(), ...
    'OffChannel', offChannel.statistics(), ...
    'ScheduledActionsObserved', actionCount, ...
    'ReceiverCompletions', rx.Completed);

    function observe(~, ~)
        actionCount = actionCount + 1;
    end
end
